// Code generated by "enumer -type=NodeType -trimprefix=NodeType -yaml -json -text -values -output=/home/janpf/Projects/gomlx/pkg/core/graph/gen_nodetype_enumer.go /home/janpf/Projects/gomlx/pkg/core/graph/gen_backend_ops.go"; DO NOT EDIT.

package graph

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _NodeTypeName = "InvalidSplitNodeAbsAddAllReduceArgMinMaxBatchNormForInferenceBatchNormForTrainingBatchNormGradientBitCountBitcastBitwiseAndBitwiseNotBitwiseOrBitwiseXorBroadcastInDimCeilClampClzComplexConcatenateConjConstantConvGeneralConvertDTypeCosDivDotDotGeneralDynamicSliceDynamicUpdateSliceEqualEqualTotalOrderErfExpExpm1FFTFloorGatherGreaterOrEqualGreaterOrEqualTotalOrderGreaterThanGreaterThanTotalOrderIdentityImagIotaIsFiniteIsNaNLessOrEqualLessOrEqualTotalOrderLessThanLessThanTotalOrderLogLog1pLogicalAndLogicalNotLogicalOrLogicalXorLogisticMaxMinMulNegNotEqualNotEqualTotalOrderPadParameterPowRNGBitGeneratorRealReduceBitwiseAndReduceBitwiseOrReduceBitwiseXorReduceLogicalAndReduceLogicalOrReduceLogicalXorReduceMaxReduceMinReduceProductReduceSumReduceWindowRemReshapeReverseRoundRsqrtScatterMaxScatterMinScatterSumSelectAndScatterMaxSelectAndScatterMinShiftLeftShiftRightArithmeticShiftRightLogicalSignSinSliceSqrtSubTanhTransposeWhere"

var _NodeTypeIndex = [...]uint16{0, 7, 16, 19, 22, 31, 40, 61, 81, 98, 106, 113, 123, 133, 142, 152, 166, 170, 175, 178, 185, 196, 200, 208, 219, 231, 234, 237, 240, 250, 262, 280, 285, 300, 303, 306, 311, 314, 319, 325, 339, 363, 374, 395, 403, 407, 411, 419, 424, 435, 456, 464, 482, 485, 490, 500, 510, 519, 529, 537, 540, 543, 546, 549, 557, 575, 578, 587, 590, 605, 609, 625, 640, 656, 672, 687, 703, 712, 721, 734, 743, 755, 758, 765, 772, 777, 782, 792, 802, 812, 831, 850, 859, 879, 896, 900, 903, 908, 912, 915, 919, 928, 933}

const _NodeTypeLowerName = "invalidsplitnodeabsaddallreduceargminmaxbatchnormforinferencebatchnormfortrainingbatchnormgradientbitcountbitcastbitwiseandbitwisenotbitwiseorbitwisexorbroadcastindimceilclampclzcomplexconcatenateconjconstantconvgeneralconvertdtypecosdivdotdotgeneraldynamicslicedynamicupdatesliceequalequaltotalordererfexpexpm1fftfloorgathergreaterorequalgreaterorequaltotalordergreaterthangreaterthantotalorderidentityimagiotaisfiniteisnanlessorequallessorequaltotalorderlessthanlessthantotalorderloglog1plogicalandlogicalnotlogicalorlogicalxorlogisticmaxminmulnegnotequalnotequaltotalorderpadparameterpowrngbitgeneratorrealreducebitwiseandreducebitwiseorreducebitwisexorreducelogicalandreducelogicalorreducelogicalxorreducemaxreduceminreduceproductreducesumreducewindowremreshapereverseroundrsqrtscattermaxscatterminscattersumselectandscattermaxselectandscatterminshiftleftshiftrightarithmeticshiftrightlogicalsignsinslicesqrtsubtanhtransposewhere"

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeTypeIndex)-1) {
		return fmt.Sprintf("NodeType(%d)", i)
	}
	return _NodeTypeName[_NodeTypeIndex[i]:_NodeTypeIndex[i+1]]
}

func (NodeType) Values() []string {
	return NodeTypeStrings()
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _NodeTypeNoOp() {
	var x [1]struct{}
	_ = x[NodeTypeInvalid-(0)]
	_ = x[NodeTypeSplitNode-(1)]
	_ = x[NodeTypeAbs-(2)]
	_ = x[NodeTypeAdd-(3)]
	_ = x[NodeTypeAllReduce-(4)]
	_ = x[NodeTypeArgMinMax-(5)]
	_ = x[NodeTypeBatchNormForInference-(6)]
	_ = x[NodeTypeBatchNormForTraining-(7)]
	_ = x[NodeTypeBatchNormGradient-(8)]
	_ = x[NodeTypeBitCount-(9)]
	_ = x[NodeTypeBitcast-(10)]
	_ = x[NodeTypeBitwiseAnd-(11)]
	_ = x[NodeTypeBitwiseNot-(12)]
	_ = x[NodeTypeBitwiseOr-(13)]
	_ = x[NodeTypeBitwiseXor-(14)]
	_ = x[NodeTypeBroadcastInDim-(15)]
	_ = x[NodeTypeCeil-(16)]
	_ = x[NodeTypeClamp-(17)]
	_ = x[NodeTypeClz-(18)]
	_ = x[NodeTypeComplex-(19)]
	_ = x[NodeTypeConcatenate-(20)]
	_ = x[NodeTypeConj-(21)]
	_ = x[NodeTypeConstant-(22)]
	_ = x[NodeTypeConvGeneral-(23)]
	_ = x[NodeTypeConvertDType-(24)]
	_ = x[NodeTypeCos-(25)]
	_ = x[NodeTypeDiv-(26)]
	_ = x[NodeTypeDot-(27)]
	_ = x[NodeTypeDotGeneral-(28)]
	_ = x[NodeTypeDynamicSlice-(29)]
	_ = x[NodeTypeDynamicUpdateSlice-(30)]
	_ = x[NodeTypeEqual-(31)]
	_ = x[NodeTypeEqualTotalOrder-(32)]
	_ = x[NodeTypeErf-(33)]
	_ = x[NodeTypeExp-(34)]
	_ = x[NodeTypeExpm1-(35)]
	_ = x[NodeTypeFFT-(36)]
	_ = x[NodeTypeFloor-(37)]
	_ = x[NodeTypeGather-(38)]
	_ = x[NodeTypeGreaterOrEqual-(39)]
	_ = x[NodeTypeGreaterOrEqualTotalOrder-(40)]
	_ = x[NodeTypeGreaterThan-(41)]
	_ = x[NodeTypeGreaterThanTotalOrder-(42)]
	_ = x[NodeTypeIdentity-(43)]
	_ = x[NodeTypeImag-(44)]
	_ = x[NodeTypeIota-(45)]
	_ = x[NodeTypeIsFinite-(46)]
	_ = x[NodeTypeIsNaN-(47)]
	_ = x[NodeTypeLessOrEqual-(48)]
	_ = x[NodeTypeLessOrEqualTotalOrder-(49)]
	_ = x[NodeTypeLessThan-(50)]
	_ = x[NodeTypeLessThanTotalOrder-(51)]
	_ = x[NodeTypeLog-(52)]
	_ = x[NodeTypeLog1p-(53)]
	_ = x[NodeTypeLogicalAnd-(54)]
	_ = x[NodeTypeLogicalNot-(55)]
	_ = x[NodeTypeLogicalOr-(56)]
	_ = x[NodeTypeLogicalXor-(57)]
	_ = x[NodeTypeLogistic-(58)]
	_ = x[NodeTypeMax-(59)]
	_ = x[NodeTypeMin-(60)]
	_ = x[NodeTypeMul-(61)]
	_ = x[NodeTypeNeg-(62)]
	_ = x[NodeTypeNotEqual-(63)]
	_ = x[NodeTypeNotEqualTotalOrder-(64)]
	_ = x[NodeTypePad-(65)]
	_ = x[NodeTypeParameter-(66)]
	_ = x[NodeTypePow-(67)]
	_ = x[NodeTypeRNGBitGenerator-(68)]
	_ = x[NodeTypeReal-(69)]
	_ = x[NodeTypeReduceBitwiseAnd-(70)]
	_ = x[NodeTypeReduceBitwiseOr-(71)]
	_ = x[NodeTypeReduceBitwiseXor-(72)]
	_ = x[NodeTypeReduceLogicalAnd-(73)]
	_ = x[NodeTypeReduceLogicalOr-(74)]
	_ = x[NodeTypeReduceLogicalXor-(75)]
	_ = x[NodeTypeReduceMax-(76)]
	_ = x[NodeTypeReduceMin-(77)]
	_ = x[NodeTypeReduceProduct-(78)]
	_ = x[NodeTypeReduceSum-(79)]
	_ = x[NodeTypeReduceWindow-(80)]
	_ = x[NodeTypeRem-(81)]
	_ = x[NodeTypeReshape-(82)]
	_ = x[NodeTypeReverse-(83)]
	_ = x[NodeTypeRound-(84)]
	_ = x[NodeTypeRsqrt-(85)]
	_ = x[NodeTypeScatterMax-(86)]
	_ = x[NodeTypeScatterMin-(87)]
	_ = x[NodeTypeScatterSum-(88)]
	_ = x[NodeTypeSelectAndScatterMax-(89)]
	_ = x[NodeTypeSelectAndScatterMin-(90)]
	_ = x[NodeTypeShiftLeft-(91)]
	_ = x[NodeTypeShiftRightArithmetic-(92)]
	_ = x[NodeTypeShiftRightLogical-(93)]
	_ = x[NodeTypeSign-(94)]
	_ = x[NodeTypeSin-(95)]
	_ = x[NodeTypeSlice-(96)]
	_ = x[NodeTypeSqrt-(97)]
	_ = x[NodeTypeSub-(98)]
	_ = x[NodeTypeTanh-(99)]
	_ = x[NodeTypeTranspose-(100)]
	_ = x[NodeTypeWhere-(101)]
}

var _NodeTypeValues = []NodeType{NodeTypeInvalid, NodeTypeSplitNode, NodeTypeAbs, NodeTypeAdd, NodeTypeAllReduce, NodeTypeArgMinMax, NodeTypeBatchNormForInference, NodeTypeBatchNormForTraining, NodeTypeBatchNormGradient, NodeTypeBitCount, NodeTypeBitcast, NodeTypeBitwiseAnd, NodeTypeBitwiseNot, NodeTypeBitwiseOr, NodeTypeBitwiseXor, NodeTypeBroadcastInDim, NodeTypeCeil, NodeTypeClamp, NodeTypeClz, NodeTypeComplex, NodeTypeConcatenate, NodeTypeConj, NodeTypeConstant, NodeTypeConvGeneral, NodeTypeConvertDType, NodeTypeCos, NodeTypeDiv, NodeTypeDot, NodeTypeDotGeneral, NodeTypeDynamicSlice, NodeTypeDynamicUpdateSlice, NodeTypeEqual, NodeTypeEqualTotalOrder, NodeTypeErf, NodeTypeExp, NodeTypeExpm1, NodeTypeFFT, NodeTypeFloor, NodeTypeGather, NodeTypeGreaterOrEqual, NodeTypeGreaterOrEqualTotalOrder, NodeTypeGreaterThan, NodeTypeGreaterThanTotalOrder, NodeTypeIdentity, NodeTypeImag, NodeTypeIota, NodeTypeIsFinite, NodeTypeIsNaN, NodeTypeLessOrEqual, NodeTypeLessOrEqualTotalOrder, NodeTypeLessThan, NodeTypeLessThanTotalOrder, NodeTypeLog, NodeTypeLog1p, NodeTypeLogicalAnd, NodeTypeLogicalNot, NodeTypeLogicalOr, NodeTypeLogicalXor, NodeTypeLogistic, NodeTypeMax, NodeTypeMin, NodeTypeMul, NodeTypeNeg, NodeTypeNotEqual, NodeTypeNotEqualTotalOrder, NodeTypePad, NodeTypeParameter, NodeTypePow, NodeTypeRNGBitGenerator, NodeTypeReal, NodeTypeReduceBitwiseAnd, NodeTypeReduceBitwiseOr, NodeTypeReduceBitwiseXor, NodeTypeReduceLogicalAnd, NodeTypeReduceLogicalOr, NodeTypeReduceLogicalXor, NodeTypeReduceMax, NodeTypeReduceMin, NodeTypeReduceProduct, NodeTypeReduceSum, NodeTypeReduceWindow, NodeTypeRem, NodeTypeReshape, NodeTypeReverse, NodeTypeRound, NodeTypeRsqrt, NodeTypeScatterMax, NodeTypeScatterMin, NodeTypeScatterSum, NodeTypeSelectAndScatterMax, NodeTypeSelectAndScatterMin, NodeTypeShiftLeft, NodeTypeShiftRightArithmetic, NodeTypeShiftRightLogical, NodeTypeSign, NodeTypeSin, NodeTypeSlice, NodeTypeSqrt, NodeTypeSub, NodeTypeTanh, NodeTypeTranspose, NodeTypeWhere}

var _NodeTypeNameToValueMap = map[string]NodeType{
	_NodeTypeName[0:7]:          NodeTypeInvalid,
	_NodeTypeLowerName[0:7]:     NodeTypeInvalid,
	_NodeTypeName[7:16]:         NodeTypeSplitNode,
	_NodeTypeLowerName[7:16]:    NodeTypeSplitNode,
	_NodeTypeName[16:19]:        NodeTypeAbs,
	_NodeTypeLowerName[16:19]:   NodeTypeAbs,
	_NodeTypeName[19:22]:        NodeTypeAdd,
	_NodeTypeLowerName[19:22]:   NodeTypeAdd,
	_NodeTypeName[22:31]:        NodeTypeAllReduce,
	_NodeTypeLowerName[22:31]:   NodeTypeAllReduce,
	_NodeTypeName[31:40]:        NodeTypeArgMinMax,
	_NodeTypeLowerName[31:40]:   NodeTypeArgMinMax,
	_NodeTypeName[40:61]:        NodeTypeBatchNormForInference,
	_NodeTypeLowerName[40:61]:   NodeTypeBatchNormForInference,
	_NodeTypeName[61:81]:        NodeTypeBatchNormForTraining,
	_NodeTypeLowerName[61:81]:   NodeTypeBatchNormForTraining,
	_NodeTypeName[81:98]:        NodeTypeBatchNormGradient,
	_NodeTypeLowerName[81:98]:   NodeTypeBatchNormGradient,
	_NodeTypeName[98:106]:       NodeTypeBitCount,
	_NodeTypeLowerName[98:106]:  NodeTypeBitCount,
	_NodeTypeName[106:113]:      NodeTypeBitcast,
	_NodeTypeLowerName[106:113]: NodeTypeBitcast,
	_NodeTypeName[113:123]:      NodeTypeBitwiseAnd,
	_NodeTypeLowerName[113:123]: NodeTypeBitwiseAnd,
	_NodeTypeName[123:133]:      NodeTypeBitwiseNot,
	_NodeTypeLowerName[123:133]: NodeTypeBitwiseNot,
	_NodeTypeName[133:142]:      NodeTypeBitwiseOr,
	_NodeTypeLowerName[133:142]: NodeTypeBitwiseOr,
	_NodeTypeName[142:152]:      NodeTypeBitwiseXor,
	_NodeTypeLowerName[142:152]: NodeTypeBitwiseXor,
	_NodeTypeName[152:166]:      NodeTypeBroadcastInDim,
	_NodeTypeLowerName[152:166]: NodeTypeBroadcastInDim,
	_NodeTypeName[166:170]:      NodeTypeCeil,
	_NodeTypeLowerName[166:170]: NodeTypeCeil,
	_NodeTypeName[170:175]:      NodeTypeClamp,
	_NodeTypeLowerName[170:175]: NodeTypeClamp,
	_NodeTypeName[175:178]:      NodeTypeClz,
	_NodeTypeLowerName[175:178]: NodeTypeClz,
	_NodeTypeName[178:185]:      NodeTypeComplex,
	_NodeTypeLowerName[178:185]: NodeTypeComplex,
	_NodeTypeName[185:196]:      NodeTypeConcatenate,
	_NodeTypeLowerName[185:196]: NodeTypeConcatenate,
	_NodeTypeName[196:200]:      NodeTypeConj,
	_NodeTypeLowerName[196:200]: NodeTypeConj,
	_NodeTypeName[200:208]:      NodeTypeConstant,
	_NodeTypeLowerName[200:208]: NodeTypeConstant,
	_NodeTypeName[208:219]:      NodeTypeConvGeneral,
	_NodeTypeLowerName[208:219]: NodeTypeConvGeneral,
	_NodeTypeName[219:231]:      NodeTypeConvertDType,
	_NodeTypeLowerName[219:231]: NodeTypeConvertDType,
	_NodeTypeName[231:234]:      NodeTypeCos,
	_NodeTypeLowerName[231:234]: NodeTypeCos,
	_NodeTypeName[234:237]:      NodeTypeDiv,
	_NodeTypeLowerName[234:237]: NodeTypeDiv,
	_NodeTypeName[237:240]:      NodeTypeDot,
	_NodeTypeLowerName[237:240]: NodeTypeDot,
	_NodeTypeName[240:250]:      NodeTypeDotGeneral,
	_NodeTypeLowerName[240:250]: NodeTypeDotGeneral,
	_NodeTypeName[250:262]:      NodeTypeDynamicSlice,
	_NodeTypeLowerName[250:262]: NodeTypeDynamicSlice,
	_NodeTypeName[262:280]:      NodeTypeDynamicUpdateSlice,
	_NodeTypeLowerName[262:280]: NodeTypeDynamicUpdateSlice,
	_NodeTypeName[280:285]:      NodeTypeEqual,
	_NodeTypeLowerName[280:285]: NodeTypeEqual,
	_NodeTypeName[285:300]:      NodeTypeEqualTotalOrder,
	_NodeTypeLowerName[285:300]: NodeTypeEqualTotalOrder,
	_NodeTypeName[300:303]:      NodeTypeErf,
	_NodeTypeLowerName[300:303]: NodeTypeErf,
	_NodeTypeName[303:306]:      NodeTypeExp,
	_NodeTypeLowerName[303:306]: NodeTypeExp,
	_NodeTypeName[306:311]:      NodeTypeExpm1,
	_NodeTypeLowerName[306:311]: NodeTypeExpm1,
	_NodeTypeName[311:314]:      NodeTypeFFT,
	_NodeTypeLowerName[311:314]: NodeTypeFFT,
	_NodeTypeName[314:319]:      NodeTypeFloor,
	_NodeTypeLowerName[314:319]: NodeTypeFloor,
	_NodeTypeName[319:325]:      NodeTypeGather,
	_NodeTypeLowerName[319:325]: NodeTypeGather,
	_NodeTypeName[325:339]:      NodeTypeGreaterOrEqual,
	_NodeTypeLowerName[325:339]: NodeTypeGreaterOrEqual,
	_NodeTypeName[339:363]:      NodeTypeGreaterOrEqualTotalOrder,
	_NodeTypeLowerName[339:363]: NodeTypeGreaterOrEqualTotalOrder,
	_NodeTypeName[363:374]:      NodeTypeGreaterThan,
	_NodeTypeLowerName[363:374]: NodeTypeGreaterThan,
	_NodeTypeName[374:395]:      NodeTypeGreaterThanTotalOrder,
	_NodeTypeLowerName[374:395]: NodeTypeGreaterThanTotalOrder,
	_NodeTypeName[395:403]:      NodeTypeIdentity,
	_NodeTypeLowerName[395:403]: NodeTypeIdentity,
	_NodeTypeName[403:407]:      NodeTypeImag,
	_NodeTypeLowerName[403:407]: NodeTypeImag,
	_NodeTypeName[407:411]:      NodeTypeIota,
	_NodeTypeLowerName[407:411]: NodeTypeIota,
	_NodeTypeName[411:419]:      NodeTypeIsFinite,
	_NodeTypeLowerName[411:419]: NodeTypeIsFinite,
	_NodeTypeName[419:424]:      NodeTypeIsNaN,
	_NodeTypeLowerName[419:424]: NodeTypeIsNaN,
	_NodeTypeName[424:435]:      NodeTypeLessOrEqual,
	_NodeTypeLowerName[424:435]: NodeTypeLessOrEqual,
	_NodeTypeName[435:456]:      NodeTypeLessOrEqualTotalOrder,
	_NodeTypeLowerName[435:456]: NodeTypeLessOrEqualTotalOrder,
	_NodeTypeName[456:464]:      NodeTypeLessThan,
	_NodeTypeLowerName[456:464]: NodeTypeLessThan,
	_NodeTypeName[464:482]:      NodeTypeLessThanTotalOrder,
	_NodeTypeLowerName[464:482]: NodeTypeLessThanTotalOrder,
	_NodeTypeName[482:485]:      NodeTypeLog,
	_NodeTypeLowerName[482:485]: NodeTypeLog,
	_NodeTypeName[485:490]:      NodeTypeLog1p,
	_NodeTypeLowerName[485:490]: NodeTypeLog1p,
	_NodeTypeName[490:500]:      NodeTypeLogicalAnd,
	_NodeTypeLowerName[490:500]: NodeTypeLogicalAnd,
	_NodeTypeName[500:510]:      NodeTypeLogicalNot,
	_NodeTypeLowerName[500:510]: NodeTypeLogicalNot,
	_NodeTypeName[510:519]:      NodeTypeLogicalOr,
	_NodeTypeLowerName[510:519]: NodeTypeLogicalOr,
	_NodeTypeName[519:529]:      NodeTypeLogicalXor,
	_NodeTypeLowerName[519:529]: NodeTypeLogicalXor,
	_NodeTypeName[529:537]:      NodeTypeLogistic,
	_NodeTypeLowerName[529:537]: NodeTypeLogistic,
	_NodeTypeName[537:540]:      NodeTypeMax,
	_NodeTypeLowerName[537:540]: NodeTypeMax,
	_NodeTypeName[540:543]:      NodeTypeMin,
	_NodeTypeLowerName[540:543]: NodeTypeMin,
	_NodeTypeName[543:546]:      NodeTypeMul,
	_NodeTypeLowerName[543:546]: NodeTypeMul,
	_NodeTypeName[546:549]:      NodeTypeNeg,
	_NodeTypeLowerName[546:549]: NodeTypeNeg,
	_NodeTypeName[549:557]:      NodeTypeNotEqual,
	_NodeTypeLowerName[549:557]: NodeTypeNotEqual,
	_NodeTypeName[557:575]:      NodeTypeNotEqualTotalOrder,
	_NodeTypeLowerName[557:575]: NodeTypeNotEqualTotalOrder,
	_NodeTypeName[575:578]:      NodeTypePad,
	_NodeTypeLowerName[575:578]: NodeTypePad,
	_NodeTypeName[578:587]:      NodeTypeParameter,
	_NodeTypeLowerName[578:587]: NodeTypeParameter,
	_NodeTypeName[587:590]:      NodeTypePow,
	_NodeTypeLowerName[587:590]: NodeTypePow,
	_NodeTypeName[590:605]:      NodeTypeRNGBitGenerator,
	_NodeTypeLowerName[590:605]: NodeTypeRNGBitGenerator,
	_NodeTypeName[605:609]:      NodeTypeReal,
	_NodeTypeLowerName[605:609]: NodeTypeReal,
	_NodeTypeName[609:625]:      NodeTypeReduceBitwiseAnd,
	_NodeTypeLowerName[609:625]: NodeTypeReduceBitwiseAnd,
	_NodeTypeName[625:640]:      NodeTypeReduceBitwiseOr,
	_NodeTypeLowerName[625:640]: NodeTypeReduceBitwiseOr,
	_NodeTypeName[640:656]:      NodeTypeReduceBitwiseXor,
	_NodeTypeLowerName[640:656]: NodeTypeReduceBitwiseXor,
	_NodeTypeName[656:672]:      NodeTypeReduceLogicalAnd,
	_NodeTypeLowerName[656:672]: NodeTypeReduceLogicalAnd,
	_NodeTypeName[672:687]:      NodeTypeReduceLogicalOr,
	_NodeTypeLowerName[672:687]: NodeTypeReduceLogicalOr,
	_NodeTypeName[687:703]:      NodeTypeReduceLogicalXor,
	_NodeTypeLowerName[687:703]: NodeTypeReduceLogicalXor,
	_NodeTypeName[703:712]:      NodeTypeReduceMax,
	_NodeTypeLowerName[703:712]: NodeTypeReduceMax,
	_NodeTypeName[712:721]:      NodeTypeReduceMin,
	_NodeTypeLowerName[712:721]: NodeTypeReduceMin,
	_NodeTypeName[721:734]:      NodeTypeReduceProduct,
	_NodeTypeLowerName[721:734]: NodeTypeReduceProduct,
	_NodeTypeName[734:743]:      NodeTypeReduceSum,
	_NodeTypeLowerName[734:743]: NodeTypeReduceSum,
	_NodeTypeName[743:755]:      NodeTypeReduceWindow,
	_NodeTypeLowerName[743:755]: NodeTypeReduceWindow,
	_NodeTypeName[755:758]:      NodeTypeRem,
	_NodeTypeLowerName[755:758]: NodeTypeRem,
	_NodeTypeName[758:765]:      NodeTypeReshape,
	_NodeTypeLowerName[758:765]: NodeTypeReshape,
	_NodeTypeName[765:772]:      NodeTypeReverse,
	_NodeTypeLowerName[765:772]: NodeTypeReverse,
	_NodeTypeName[772:777]:      NodeTypeRound,
	_NodeTypeLowerName[772:777]: NodeTypeRound,
	_NodeTypeName[777:782]:      NodeTypeRsqrt,
	_NodeTypeLowerName[777:782]: NodeTypeRsqrt,
	_NodeTypeName[782:792]:      NodeTypeScatterMax,
	_NodeTypeLowerName[782:792]: NodeTypeScatterMax,
	_NodeTypeName[792:802]:      NodeTypeScatterMin,
	_NodeTypeLowerName[792:802]: NodeTypeScatterMin,
	_NodeTypeName[802:812]:      NodeTypeScatterSum,
	_NodeTypeLowerName[802:812]: NodeTypeScatterSum,
	_NodeTypeName[812:831]:      NodeTypeSelectAndScatterMax,
	_NodeTypeLowerName[812:831]: NodeTypeSelectAndScatterMax,
	_NodeTypeName[831:850]:      NodeTypeSelectAndScatterMin,
	_NodeTypeLowerName[831:850]: NodeTypeSelectAndScatterMin,
	_NodeTypeName[850:859]:      NodeTypeShiftLeft,
	_NodeTypeLowerName[850:859]: NodeTypeShiftLeft,
	_NodeTypeName[859:879]:      NodeTypeShiftRightArithmetic,
	_NodeTypeLowerName[859:879]: NodeTypeShiftRightArithmetic,
	_NodeTypeName[879:896]:      NodeTypeShiftRightLogical,
	_NodeTypeLowerName[879:896]: NodeTypeShiftRightLogical,
	_NodeTypeName[896:900]:      NodeTypeSign,
	_NodeTypeLowerName[896:900]: NodeTypeSign,
	_NodeTypeName[900:903]:      NodeTypeSin,
	_NodeTypeLowerName[900:903]: NodeTypeSin,
	_NodeTypeName[903:908]:      NodeTypeSlice,
	_NodeTypeLowerName[903:908]: NodeTypeSlice,
	_NodeTypeName[908:912]:      NodeTypeSqrt,
	_NodeTypeLowerName[908:912]: NodeTypeSqrt,
	_NodeTypeName[912:915]:      NodeTypeSub,
	_NodeTypeLowerName[912:915]: NodeTypeSub,
	_NodeTypeName[915:919]:      NodeTypeTanh,
	_NodeTypeLowerName[915:919]: NodeTypeTanh,
	_NodeTypeName[919:928]:      NodeTypeTranspose,
	_NodeTypeLowerName[919:928]: NodeTypeTranspose,
	_NodeTypeName[928:933]:      NodeTypeWhere,
	_NodeTypeLowerName[928:933]: NodeTypeWhere,
}

var _NodeTypeNames = []string{
	_NodeTypeName[0:7],
	_NodeTypeName[7:16],
	_NodeTypeName[16:19],
	_NodeTypeName[19:22],
	_NodeTypeName[22:31],
	_NodeTypeName[31:40],
	_NodeTypeName[40:61],
	_NodeTypeName[61:81],
	_NodeTypeName[81:98],
	_NodeTypeName[98:106],
	_NodeTypeName[106:113],
	_NodeTypeName[113:123],
	_NodeTypeName[123:133],
	_NodeTypeName[133:142],
	_NodeTypeName[142:152],
	_NodeTypeName[152:166],
	_NodeTypeName[166:170],
	_NodeTypeName[170:175],
	_NodeTypeName[175:178],
	_NodeTypeName[178:185],
	_NodeTypeName[185:196],
	_NodeTypeName[196:200],
	_NodeTypeName[200:208],
	_NodeTypeName[208:219],
	_NodeTypeName[219:231],
	_NodeTypeName[231:234],
	_NodeTypeName[234:237],
	_NodeTypeName[237:240],
	_NodeTypeName[240:250],
	_NodeTypeName[250:262],
	_NodeTypeName[262:280],
	_NodeTypeName[280:285],
	_NodeTypeName[285:300],
	_NodeTypeName[300:303],
	_NodeTypeName[303:306],
	_NodeTypeName[306:311],
	_NodeTypeName[311:314],
	_NodeTypeName[314:319],
	_NodeTypeName[319:325],
	_NodeTypeName[325:339],
	_NodeTypeName[339:363],
	_NodeTypeName[363:374],
	_NodeTypeName[374:395],
	_NodeTypeName[395:403],
	_NodeTypeName[403:407],
	_NodeTypeName[407:411],
	_NodeTypeName[411:419],
	_NodeTypeName[419:424],
	_NodeTypeName[424:435],
	_NodeTypeName[435:456],
	_NodeTypeName[456:464],
	_NodeTypeName[464:482],
	_NodeTypeName[482:485],
	_NodeTypeName[485:490],
	_NodeTypeName[490:500],
	_NodeTypeName[500:510],
	_NodeTypeName[510:519],
	_NodeTypeName[519:529],
	_NodeTypeName[529:537],
	_NodeTypeName[537:540],
	_NodeTypeName[540:543],
	_NodeTypeName[543:546],
	_NodeTypeName[546:549],
	_NodeTypeName[549:557],
	_NodeTypeName[557:575],
	_NodeTypeName[575:578],
	_NodeTypeName[578:587],
	_NodeTypeName[587:590],
	_NodeTypeName[590:605],
	_NodeTypeName[605:609],
	_NodeTypeName[609:625],
	_NodeTypeName[625:640],
	_NodeTypeName[640:656],
	_NodeTypeName[656:672],
	_NodeTypeName[672:687],
	_NodeTypeName[687:703],
	_NodeTypeName[703:712],
	_NodeTypeName[712:721],
	_NodeTypeName[721:734],
	_NodeTypeName[734:743],
	_NodeTypeName[743:755],
	_NodeTypeName[755:758],
	_NodeTypeName[758:765],
	_NodeTypeName[765:772],
	_NodeTypeName[772:777],
	_NodeTypeName[777:782],
	_NodeTypeName[782:792],
	_NodeTypeName[792:802],
	_NodeTypeName[802:812],
	_NodeTypeName[812:831],
	_NodeTypeName[831:850],
	_NodeTypeName[850:859],
	_NodeTypeName[859:879],
	_NodeTypeName[879:896],
	_NodeTypeName[896:900],
	_NodeTypeName[900:903],
	_NodeTypeName[903:908],
	_NodeTypeName[908:912],
	_NodeTypeName[912:915],
	_NodeTypeName[915:919],
	_NodeTypeName[919:928],
	_NodeTypeName[928:933],
}

// NodeTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func NodeTypeString(s string) (NodeType, error) {
	if val, ok := _NodeTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _NodeTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to NodeType values", s)
}

// NodeTypeValues returns all values of the enum
func NodeTypeValues() []NodeType {
	return _NodeTypeValues
}

// NodeTypeStrings returns a slice of all String values of the enum
func NodeTypeStrings() []string {
	strs := make([]string, len(_NodeTypeNames))
	copy(strs, _NodeTypeNames)
	return strs
}

// IsANodeType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i NodeType) IsANodeType() bool {
	for _, v := range _NodeTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for NodeType
func (i NodeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for NodeType
func (i *NodeType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("NodeType should be a string, got %s", data)
	}

	var err error
	*i, err = NodeTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for NodeType
func (i NodeType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for NodeType
func (i *NodeType) UnmarshalText(text []byte) error {
	var err error
	*i, err = NodeTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for NodeType
func (i NodeType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for NodeType
func (i *NodeType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = NodeTypeString(s)
	return err
}
