// Code generated by "enumer -type Type -trimprefix=Type -output=gen_type_enumer.go activations.go"; DO NOT EDIT.

package activations

import (
	"fmt"
	"strings"
)

const _TypeName = "NoneReluSigmoidHardSigmoidLeakyReluSeluSwishHardSwishSiluTanhGeluGeluApprox"

var _TypeIndex = [...]uint8{0, 4, 8, 15, 26, 35, 39, 44, 53, 57, 61, 65, 75}

const _TypeLowerName = "nonerelusigmoidhardsigmoidleakyreluseluswishhardswishsilutanhgelugeluapprox"

func (i Type) String() string {
	if i < 0 || i >= Type(len(_TypeIndex)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _TypeName[_TypeIndex[i]:_TypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TypeNoOp() {
	var x [1]struct{}
	_ = x[TypeNone-(0)]
	_ = x[TypeRelu-(1)]
	_ = x[TypeSigmoid-(2)]
	_ = x[TypeHardSigmoid-(3)]
	_ = x[TypeLeakyRelu-(4)]
	_ = x[TypeSelu-(5)]
	_ = x[TypeSwish-(6)]
	_ = x[TypeHardSwish-(7)]
	_ = x[TypeSilu-(8)]
	_ = x[TypeTanh-(9)]
	_ = x[TypeGelu-(10)]
	_ = x[TypeGeluApprox-(11)]
}

var _TypeValues = []Type{TypeNone, TypeRelu, TypeSigmoid, TypeHardSigmoid, TypeLeakyRelu, TypeSelu, TypeSwish, TypeHardSwish, TypeSilu, TypeTanh, TypeGelu, TypeGeluApprox}

var _TypeNameToValueMap = map[string]Type{
	_TypeName[0:4]:        TypeNone,
	_TypeLowerName[0:4]:   TypeNone,
	_TypeName[4:8]:        TypeRelu,
	_TypeLowerName[4:8]:   TypeRelu,
	_TypeName[8:15]:       TypeSigmoid,
	_TypeLowerName[8:15]:  TypeSigmoid,
	_TypeName[15:26]:      TypeHardSigmoid,
	_TypeLowerName[15:26]: TypeHardSigmoid,
	_TypeName[26:35]:      TypeLeakyRelu,
	_TypeLowerName[26:35]: TypeLeakyRelu,
	_TypeName[35:39]:      TypeSelu,
	_TypeLowerName[35:39]: TypeSelu,
	_TypeName[39:44]:      TypeSwish,
	_TypeLowerName[39:44]: TypeSwish,
	_TypeName[44:53]:      TypeHardSwish,
	_TypeLowerName[44:53]: TypeHardSwish,
	_TypeName[53:57]:      TypeSilu,
	_TypeLowerName[53:57]: TypeSilu,
	_TypeName[57:61]:      TypeTanh,
	_TypeLowerName[57:61]: TypeTanh,
	_TypeName[61:65]:      TypeGelu,
	_TypeLowerName[61:65]: TypeGelu,
	_TypeName[65:75]:      TypeGeluApprox,
	_TypeLowerName[65:75]: TypeGeluApprox,
}

var _TypeNames = []string{
	_TypeName[0:4],
	_TypeName[4:8],
	_TypeName[8:15],
	_TypeName[15:26],
	_TypeName[26:35],
	_TypeName[35:39],
	_TypeName[39:44],
	_TypeName[44:53],
	_TypeName[53:57],
	_TypeName[57:61],
	_TypeName[61:65],
	_TypeName[65:75],
}

// TypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TypeString(s string) (Type, error) {
	if val, ok := _TypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Type values", s)
}

// TypeValues returns all values of the enum
func TypeValues() []Type {
	return _TypeValues
}

// TypeStrings returns a slice of all String values of the enum
func TypeStrings() []string {
	strs := make([]string, len(_TypeNames))
	copy(strs, _TypeNames)
	return strs
}

// IsAType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Type) IsAType() bool {
	for _, v := range _TypeValues {
		if i == v {
			return true
		}
	}
	return false
}
