// Code generated by "enumer -type Type -trimprefix=Type -output=gen_type_enumer.go activations.go"; DO NOT EDIT.

package activations

import (
	"fmt"
	"strings"
)

const _TypeName = "NoneReluSigmoidLeakyReluSeluSwishHardSwishSiluTanhGeluGeluApprox"

var _TypeIndex = [...]uint8{0, 4, 8, 15, 24, 28, 33, 42, 46, 50, 54, 64}

const _TypeLowerName = "nonerelusigmoidleakyreluseluswishhardswishsilutanhgelugeluapprox"

func (i Type) String() string {
	if i < 0 || i >= Type(len(_TypeIndex)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _TypeName[_TypeIndex[i]:_TypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TypeNoOp() {
	var x [1]struct{}
	_ = x[TypeNone-(0)]
	_ = x[TypeRelu-(1)]
	_ = x[TypeSigmoid-(2)]
	_ = x[TypeLeakyRelu-(3)]
	_ = x[TypeSelu-(4)]
	_ = x[TypeSwish-(5)]
	_ = x[TypeHardSwish-(6)]
	_ = x[TypeSilu-(7)]
	_ = x[TypeTanh-(8)]
	_ = x[TypeGelu-(9)]
	_ = x[TypeGeluApprox-(10)]
}

var _TypeValues = []Type{TypeNone, TypeRelu, TypeSigmoid, TypeLeakyRelu, TypeSelu, TypeSwish, TypeHardSwish, TypeSilu, TypeTanh, TypeGelu, TypeGeluApprox}

var _TypeNameToValueMap = map[string]Type{
	_TypeName[0:4]:        TypeNone,
	_TypeLowerName[0:4]:   TypeNone,
	_TypeName[4:8]:        TypeRelu,
	_TypeLowerName[4:8]:   TypeRelu,
	_TypeName[8:15]:       TypeSigmoid,
	_TypeLowerName[8:15]:  TypeSigmoid,
	_TypeName[15:24]:      TypeLeakyRelu,
	_TypeLowerName[15:24]: TypeLeakyRelu,
	_TypeName[24:28]:      TypeSelu,
	_TypeLowerName[24:28]: TypeSelu,
	_TypeName[28:33]:      TypeSwish,
	_TypeLowerName[28:33]: TypeSwish,
	_TypeName[33:42]:      TypeHardSwish,
	_TypeLowerName[33:42]: TypeHardSwish,
	_TypeName[42:46]:      TypeSilu,
	_TypeLowerName[42:46]: TypeSilu,
	_TypeName[46:50]:      TypeTanh,
	_TypeLowerName[46:50]: TypeTanh,
	_TypeName[50:54]:      TypeGelu,
	_TypeLowerName[50:54]: TypeGelu,
	_TypeName[54:64]:      TypeGeluApprox,
	_TypeLowerName[54:64]: TypeGeluApprox,
}

var _TypeNames = []string{
	_TypeName[0:4],
	_TypeName[4:8],
	_TypeName[8:15],
	_TypeName[15:24],
	_TypeName[24:28],
	_TypeName[28:33],
	_TypeName[33:42],
	_TypeName[42:46],
	_TypeName[46:50],
	_TypeName[50:54],
	_TypeName[54:64],
}

// TypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TypeString(s string) (Type, error) {
	if val, ok := _TypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Type values", s)
}

// TypeValues returns all values of the enum
func TypeValues() []Type {
	return _TypeValues
}

// TypeStrings returns a slice of all String values of the enum
func TypeStrings() []string {
	strs := make([]string, len(_TypeNames))
	copy(strs, _TypeNames)
	return strs
}

// IsAType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Type) IsAType() bool {
	for _, v := range _TypeValues {
		if i == v {
			return true
		}
	}
	return false
}
