// Copyright 2023-2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

package train

import (
	"iter"
	"path"

	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/gomlx/core/graph"
	"github.com/gomlx/gomlx/core/tensors"
	"github.com/gomlx/gomlx/ml/model"
	"github.com/gomlx/gomlx/ml/model/initializer"
	"github.com/gomlx/gomlx/support/exceptions"
	"github.com/pkg/errors"
)

// AccumulatedGradientsScope is the scope under which we accumulated gradients.
const AccumulatedGradientsScope = "acc_grads"

// OptimizeWithGradients is the interface an optimizer needs to support to be used with AccumulateGradients.
type OptimizeWithGradients interface {
	// UpdateGraphWithGradients works like Optimizers.Interface.UpdateGraph, but takes as input the gradients themselves,
	// as opposed to the loss.
	UpdateGraphWithGradients(scope *model.Scope, gradients []*graph.Node, lossDType dtypes.DType)
}

// AccumulateGradients configures the trainer to accumulate numAccumulatingSteps of gradients before actually applying them.
// globalStep will only be updated after numAccumulatingSteps are fed with Trainer.TrainStep.
//
// Notice that setting this makes the concept of "TrainStep" and "GlobalStep" diverge: there will now be numAccumulatingSteps "train steps"
// per "global step".
func (r *Trainer) AccumulateGradients(numAccumulatingSteps int) error {
	if r.optimizer == nil {
		return errors.New("optimizer is nil!?")
	}
	if _, ok := r.optimizer.(OptimizeWithGradients); !ok {
		return errors.Errorf("optimizer %T does not implement OptimizeWithGradients -- to use AccumulateGradients use an optmizer that supports it (e.g.: SGD, Adam)", r.optimizer)
	}
	r.accumulateGradients = true
	r.accumulateGradientsSteps = numAccumulatingSteps
	r.accumulateGradientsCurrentStep = 0
	return nil
}

// NumAccumulatingSteps return the number of accumulating steps, if AccumulateGradients is being used.
// Otherwise, it returns 0.
func (r *Trainer) NumAccumulatingSteps() int {
	return r.accumulateGradientsSteps
}

// iterTrainableAndAccumulatorVariables iterates over all the trainable variables (in the current graph g) and yields
// both the trainable variable and the corresponding gradient accumulator variable.
func iterTrainableAndAccumulatorVariables(scope *model.Scope, g *graph.Graph) iter.Seq2[*model.Variable, *model.Variable] {
	return func(yield func(trainable, accumulator *model.Variable) bool) {
		for v := range scope.IterVariables() {
			if !v.Trainable || !v.InUseByGraph(g) {
				// We are only interested in trainable variables used by this graph.
				continue
			}
			originalScope := v.Scope()
			originalName := v.Name()
			scopePath := path.Join("/", AccumulatedGradientsScope, originalScope)
			shape := v.Shape().Clone()
			accumulator := scope.Store().Scope(scopePath).
				WithInitializer(initializer.Zero).
				VariableWithShape(originalName, shape).
				SetTrainable(false)
			if !yield(v, accumulator) {
				return
			}
		}
	}
}

// accumulateStepGraphImpl implements the computation graph to generate and accumulate one step.
// It is called by the scope executor (`r.accumulateGradientsExecMap`) everytime a graph needs to be built:
// the first time, when the batch size changes, or the dataset spec changes.
//
// If applyGradients is true, it will also apply the accumulated gradients.
func (r *Trainer) accumulateStepGraphImpl(spec any, scope *model.Scope, inputs, labels []*graph.Node, applyGradients bool) (metrics []*graph.Node) {
	g := inputs[0].Graph()
	scope.Store().SetTraining(g, true) // Some layers behave differently if in training.

	// AddLoss generated by the given lossFn.
	predictions := r.modelFn(scope, spec, inputs)
	if r.lossFn != nil {
		baseLoss := r.lossFnScalarLoss(scope, labels, predictions)
		SetLossNoRegularization(baseLoss)
		AddLoss(baseLoss)
	}

	// Store total loss as a variable, so it can be used by metrics.
	loss := GetLosses(g)
	if loss == nil {
		exceptions.Panicf("no loss function defined (or it returned nil), and no loss set with AddLoss(), " +
			"there is nothing to optimize!?")
	}

	// Metrics updates. They include: batch loss, exponential moving average of the batch loss.
	if len(predictions) == 0 {
		// We create a zero prediction (same dtype as loss), because the metrics require something.
		predictions = []*graph.Node{graph.ScalarZero(g, loss.DType())}
	}
	metrics = r.metricsUpdatesGraph(scope, labels, predictions, r.trainMetrics)

	// Calculate and accumulate gradients: grads is a slice of gradients for each trainable variable, in
	// the same order as the variables are iterated.
	grads := scope.BuildTrainableVariablesGradientsGraph(loss)
	numTrainable := len(grads)
	varIdx := 0
	for v, accVar := range iterTrainableAndAccumulatorVariables(scope, g) {
		if varIdx > numTrainable {
			exceptions.Panicf("more gradients (%d) than trainable variables, this should not happen!", len(grads))
		}
		shape := v.Shape()
		if !shape.Equal(grads[varIdx].Shape()) {
			exceptions.Panicf(
				"shape mismatch between variable %q (shape=%s) and the correspoding gradient #%d (shape=%s)",
				v.Path(), v.Shape(), varIdx, grads[varIdx].Shape())
		}
		// Store updated variable, and update gradient to accumulated value.
		grads[varIdx] = graph.Add(accVar.NodeValue(g), grads[varIdx])
		accVar.SetNodeValue(grads[varIdx])
		varIdx++
	}
	if !applyGradients {
		// Not yet time to apply the gradients, return.
		return
	}

	// Take the mean of the accumulated gradients.
	ratio := 1.0 / float64(r.accumulateGradientsSteps)
	for ii := range grads {
		grads[ii] = graph.MulScalar(grads[ii], ratio)
	}

	// Apply mean of accumulated gradients with optimizer:
	lossDType := loss.DType()
	opt := r.optimizer.(OptimizeWithGradients)
	opt.UpdateGraphWithGradients(scope, grads, lossDType)

	// Execute registered ScopeGraphFn hooks for the current graph.
	ExecPerStepUpdateGraphFn(g)

	// Reset accumulated gradients.
	for _, accVar := range iterTrainableAndAccumulatorVariables(scope, g) {
		accVar.SetNodeValue(graph.Zeros(g, accVar.Shape()))
	}
	return
}

func (r *Trainer) accumulateStepNoApplyGraph(spec any, scope *model.Scope, inputs, labels []*graph.Node) (metrics []*graph.Node) {
	return r.accumulateStepGraphImpl(spec, scope, inputs, labels, false)
}

func (r *Trainer) accumulateStepAndApplyGraph(spec any, scope *model.Scope, inputs, labels []*graph.Node) (metrics []*graph.Node) {
	return r.accumulateStepGraphImpl(spec, scope, inputs, labels, true)
}

func (r *Trainer) trainStepWithAccumulateGradients(spec any, inputs, labels []*tensors.Tensor) (metrics []*tensors.Tensor, err error) {
	r.accumulateGradientsCurrentStep++
	if r.accumulateGradientsCurrentStep < r.accumulateGradientsSteps {
		return r.callGraphFn(r.accumulateStepNoApplyGraph, TrainType, r.accumulateGradientsExecMap, spec, inputs, labels)
	}
	r.accumulateGradientsCurrentStep = 0
	return r.callGraphFn(r.accumulateStepAndApplyGraph, TrainType, r.accumulateGradientsAndApplyExecMap, spec, inputs, labels)
}
