// Copyright 2023-2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

// Package train holds tools to help run a training loop.
//
// It provides various levels of tooling, from supporting training
// one step, or a full loop. But it should serve also as an example
// that users that needs more flexibility can start from to create
// their own training loops.
package train

//go:generate go run ../../internal/cmd/trainer_aliases

import (
	"fmt"
	"io"
	"iter"
	"slices"

	"github.com/gomlx/compute"
	"github.com/gomlx/compute/distributed"
	"github.com/gomlx/gomlx/core/graph"
	"github.com/gomlx/gomlx/core/tensors"
	"github.com/gomlx/gomlx/core/tensors/dtensor"
	"github.com/gomlx/gomlx/ml/model"
	"github.com/gomlx/gomlx/ml/train/loss"
	"github.com/gomlx/gomlx/ml/train/metric"
	"github.com/gomlx/gomlx/ml/train/optimizer"
	"github.com/gomlx/gomlx/support/exceptions"
	"github.com/pkg/errors"
)

const (
	// TrainerAbsoluteScope used for Scope parameters related to the trainer.
	TrainerAbsoluteScope = model.ScopeSeparator + "trainer"

	// TrainerMainLossGraphParamKey is the graph params key that maps to the
	// node with the accumulated main losses in the model.
	TrainerMainLossGraphParamKey = "trainer_main_loss"

	// TrainerRegularizationLossGraphParamKey is the graph params key that maps to the
	// node with the accumulated regularization losses in the model.
	TrainerRegularizationLossGraphParamKey = "trainer_regularization_loss"

	// TrainerLossGraphParamKey is deprecated.
	// Deprecated: use TrainerMainLossGraphParamKey and TrainerRegularizationLossGraphParamKey instead.
	TrainerLossGraphParamKey = "trainer_loss"

	// TrainerLossNoRegularizationGraphParamKey is deprecated.
	// Deprecated: use TrainerMainLossGraphParamKey instead.
	TrainerLossNoRegularizationGraphParamKey = "trainer_loss_no_regularization"

	// TrainerPerStepUpdateGraphFnParamKey is used by AddPerStepUpdateGraphFn.
	TrainerPerStepUpdateGraphFnParamKey = "trainer_per_step_update_graph_fn"
)

// Trainer is a helper object to orchestrate a training step and evaluation.
//
// Given the inputs and labels, it deals with executing a training step (TrainStep) and
// evaluation (EvalStep and Eval), calling the loss and optimizer and running metrics.
//
// See Loop for a flexible and extensible (different UIs) way to run this in a training loop.
type Trainer struct {
	backend   compute.Backend
	store     *model.Store
	deviceNum compute.DeviceNum
	modelFn   ModelFn
	lossFn    LossFn
	optimizer optimizer.Interface

	// Distribute execution:
	deviceAssignment []compute.DeviceNum // Optional.

	// maxExecutors to cache. It will fail after that. One executor is created
	// per `spec` value, so this is the same as the max number of different `spec`
	// values seen.
	maxExecutors              int
	inputsAndLabelsLenPerSpec map[any][2]int

	// Training data
	trainStepExecMap map[any]*model.Exec
	trainMetrics     []metric.Interface

	// Accumulate gradients mode:
	accumulateGradients                bool
	accumulateGradientsSteps           int
	accumulateGradientsCurrentStep     int
	accumulateGradientsExecMap         map[any]*model.Exec
	accumulateGradientsAndApplyExecMap map[any]*model.Exec

	// Eval data
	evalStepExecMap map[any]*model.Exec
	evalMetrics     []metric.Interface

	// BatchNormAverages data
	batchNormStepExecMap map[any]*model.Exec

	inputsDynamicAxes [][]string
	labelsDynamicAxes [][]string

	// onExecCreationHandlers are hooks called during executor creation.
	onExecCreationHandlers []OnExecFn
}

// ModelFn is the canonical computation graph building function that takes as input a `spec` (given by the dataset)
// and a slice of `inputs` (even if just one) generated by a Dataset, and as output a slice (even if only one) of
// the `predictions` (or sometimes the logits).
//
// The `predictions` output by ModelFn is fed to a LossFn and to MetricsFn during training.
//
// Notice `spec` is opaque to train package, it's passed from the [Dataset] to the [ModelFn], and its
// meaning is determined by the [Dataset] used. For static case (where data is always the same) it can simply be
// nil. Each value of `spec` is mapped to different computation graphs by the [Trainer].
//
// In most of the cases, on can instead simply use a [ModelFnCompatible] signature for the model function,
// and the [NewTrainer] will automatically wrap it and convert it to a [ModelFn].
//
// E.g.: A simple image classification modelFn that is ModelFnCompatible (single input, single output) and
// will automatically get converted to a [ModelFn] signature:
//
//	func MyImageClassificationModel(scope *model.Scope, image *graph.Node) (prediction *graph.Node)
type ModelFn func(scope *model.Scope, spec any, inputs []*graph.Node) (predictions []*graph.Node)

// LossFn takes the output of ModelFn (called predictions, but it could be the logits),
// and the labels (coming out of Dataset.Yield()), and outputs the scalar loss, that can
// be used for training.
//
// For some types of self-supervised models for which there are no labels, the labels can be empty.
//
// Most of the predefined losses in package `gomlx/ml/train/losses` assume labels and predictions are
// both of length one. For multi-head models, it's very easy to write a small custom LossFn that splits
// the slice and send each label/prediction pair to a predefined loss.
//
// Interface is defined in the losses package.
type LossFn = loss.LossFn

// DefaultMaxExecutors used for Trainer objects. Each different `spec` value from a Dataset triggers
// the creation of a new executor.
//
// If using AccumulateGradients, there will be 2 graphs per shape of input data: one to accumulate the gradients
// and another to accumulate and apply the gradients.
var DefaultMaxExecutors = 50

// GraphType can be TrainGraph or EvalGraph, when there needs to be a distinction.
type GraphType int

const (
	TrainType GraphType = iota
	EvalType
	BatchNormAveragesType
)

// NewTrainer constructs a trainer that can be used for training steps and evaluation. It also creates a new Scope
// for model, which will hold the variables, hyperparameters, and other information. It can be changed by the user.
//
// Its arguments are:
//
//   - backend needed to create and compile computation graphs.
//
//   - scope (will) hold the variables, hyperparameters, and related information for the model.
//
//   - modelFn builds the graph that transforms inputs into predictions (or logits). It takes a ModelFn function
//     or a function with a compatible signature, see the [ModelFnCompatible] constraint, that gets automatically
//     converted to [ModelFn] (e.g., omitting the spec parameter, or returning 1-3 nodes).
//
//   - lossFn takes the predictions (the output of modelFn) and the labels and outputs the loss. If the
//     returned loss is not a scalar, it will be ReduceAllMean to a scalar.
//     There are several standard losses available in gomlx/ml/train/losses package.
//     They can simply be used as is, or called by arbitrary custom losses.
//     It can also be set to nil, if one is providing loss terms with `AddMainLoss` -- e.g.: for unsupervised training.
//
//   - optimizer (e.g: optimizer.StochasticGradientDescent) is the methodology to improve the model variables (aka.
//     parameters or weights) to minimize the loss (the output of lossFn), typically using gradient descent.
//
//   - trainMetrics are output by trainer.TrainStep after each step. Here it's recommended to use moving average
//     types of metrics, since the model is changing so a mean wouldn't make sense. The mean loss of the batch and
//     a moving average of the loss is always included (the first two) by default. It's ok to be empty (nil).
//
//   - evalMetrics are output by trainer.EvalStep and trainer.Eval. Here it's recommend to use mean metrics, since the model
//     is presumably frozen, and it sees each example exactly once. The mean of the loss of the dataset is always provided
//     as the first metric. It's ok to be empty (nil).
func NewTrainer[ModelFnT ModelFnCompatible](backend compute.Backend, store *model.Store,
	modelFn ModelFnT, lossFn LossFn, theOptimizer optimizer.Interface,
	trainMetrics, evalMetrics []metric.Interface) *Trainer {

	r := &Trainer{
		backend:   backend,
		store:     store,
		deviceNum: 0,
		modelFn:   createModelFnWrapper(modelFn),
		lossFn:    lossFn,
		optimizer: theOptimizer,

		maxExecutors:              DefaultMaxExecutors,
		inputsAndLabelsLenPerSpec: make(map[any][2]int),
		trainStepExecMap:          make(map[any]*model.Exec),
		evalStepExecMap:           make(map[any]*model.Exec),
		batchNormStepExecMap:      make(map[any]*model.Exec),

		accumulateGradientsExecMap:         make(map[any]*model.Exec),
		accumulateGradientsAndApplyExecMap: make(map[any]*model.Exec),
	}

	// Delete variables that should forcefully be reinitialized every time the model is retrained.
	optScope := store.Scope(optimizer.Scope)
	err := optScope.DeleteVariable(optimizer.ParamLearningRate)
	if err != nil {
		panic(err)
	}

	// Create a scope executor for TrainStep. Automatically include batch loss and moving average loss metrics.
	numMetrics := len(trainMetrics) + 2
	lossAndMetrics := make([]metric.Interface, 0, numMetrics)
	batchLossFn := func(_ *model.Scope, labels, predictions []*graph.Node) *graph.Node {
		// Assume lossVar has already been set.
		g := predictions[0].Graph()
		theLoss := TotalLoss(g)
		if theLoss == nil {

			return graph.ScalarZero(g, predictions[0].DType())
		}
		return theLoss
	}
	lossAndMetrics = append(
		lossAndMetrics,
		metric.NewBaseMetric("Loss", "loss", metric.LossMetricType, batchLossFn, nil),
	)
	lossAndMetrics = append(
		lossAndMetrics,
		metric.NewExponentialMovingAverageMetric(
			"Moving Average Loss",
			"~loss",
			metric.LossMetricType,
			batchLossFn,
			nil,
			0.01,
		),
	)

	lossAndMetrics = append(lossAndMetrics, trainMetrics...)
	r.trainMetrics = lossAndMetrics

	// Create a scope executor for EvalStep. Automatically include the mean loss metric as the first eval metric.
	numMetrics = len(evalMetrics) + 1
	lossAndMetrics = make([]metric.Interface, 0, numMetrics)
	lossAndMetrics = append(
		lossAndMetrics,
		metric.NewMeanMetric("Mean Loss", "#loss", metric.LossMetricType, batchLossFn, nil),
	)
	lossAndMetrics = append(lossAndMetrics, evalMetrics...)
	r.evalMetrics = lossAndMetrics
	return r
}

// WithDeviceAssignemnt sets the backend device assignment to use.
//
// This works for both distributed and normal (single device) training. The later uses only one device where to
// execute the training/evaluation steps.
//
// A nil value (the default) is valid, in which case it uses the backend's default, which is usually simply the
// sequential devices starting from 0.
func (r *Trainer) WithDeviceAssignment(deviceAssignment ...compute.DeviceNum) *Trainer {
	if deviceAssignment == nil {
		r.deviceAssignment = nil
		return r
	}
	r.deviceAssignment = slices.Clone(deviceAssignment)
	return r
}

// WithMainLossMetric configures the trainer to also include the "no-reg" loss metrics,
// showing the model loss without regularization.
func (r *Trainer) WithMainLossMetric() *Trainer {
	lossNoRegularizationFn := func(scope *model.Scope, labels, predictions []*graph.Node) *graph.Node {
		g := predictions[0].Graph()
		theLoss := GetMainLoss(g)
		if theLoss == nil {
			return graph.ScalarZero(g, predictions[0].DType())
		}
		return theLoss
	}

	// Insert "Moving Average Loss (no-reg)" right after the first two loss metrics (Loss and Moving Average Loss)
	hasMainLossMetric := false
	for _, m := range r.trainMetrics {
		if m.Name() == "Moving Average Loss (no-reg)" {
			hasMainLossMetric = true
			break
		}
	}
	if !hasMainLossMetric {
		var newTrainMetric metric.Interface = metric.NewExponentialMovingAverageMetric("Moving Average Loss (no-reg)", "~loss_no_reg", metric.LossMetricType,
			lossNoRegularizationFn, nil, 0.01)
		r.trainMetrics = slices.Insert(r.trainMetrics, 2, newTrainMetric)
	}

	// Insert "Mean Loss (no-reg)" right after the first evaluation metric (Mean Loss)
	hasEvalMainLossMetric := false
	for _, m := range r.evalMetrics {
		if m.Name() == "Mean Loss (no-reg)" {
			hasEvalMainLossMetric = true
			break
		}
	}
	if !hasEvalMainLossMetric {
		var newEvalMetric metric.Interface = metric.NewMeanMetric("Mean Loss (no-reg)", "#loss_no_reg", metric.LossMetricType,
			lossNoRegularizationFn, nil)
		r.evalMetrics = slices.Insert(r.evalMetrics, 1, newEvalMetric)
	}
	return r
}

// iterateExecs returns an iterator over all executors maintained by the Trainer.
func (r *Trainer) iterateExecs() iter.Seq[*model.Exec] {
	return func(yield func(*model.Exec) bool) {
		for _, exec := range r.trainStepExecMap {
			if !yield(exec) {
				return
			}
		}
		for _, exec := range r.evalStepExecMap {
			if !yield(exec) {
				return
			}
		}
		for _, exec := range r.batchNormStepExecMap {
			if !yield(exec) {
				return
			}
		}
		for _, exec := range r.accumulateGradientsExecMap {
			if !yield(exec) {
				return
			}
		}
		for _, exec := range r.accumulateGradientsAndApplyExecMap {
			if !yield(exec) {
				return
			}
		}
	}
}

// Backend returns the current Backend.
func (r *Trainer) Backend() compute.Backend {
	return r.backend
}

// Store returns the current Store. See SetScope to change it.
func (r *Trainer) Store() *model.Store {
	return r.store
}

// SetStore associates the given [model.Store] to the trainer.
//
// Should be called before any calls to Train or Evaluate, otherwise
// the results are undefined.
func (r *Trainer) SetStore(store *model.Store) *Trainer {
	r.store = store
	for exec := range r.iterateExecs() {
		exec.SetStore(store)
	}
	return r
}

// WithMaxExecutors configure the Trainer to allow these many different executors to be created before failing.
//
// One executor is created per each different shape of input, times one for training, and one for evaluation (if
// Trainer.Eval is being used).
// The default is DefaultMaxExecutors.
//
// It returns the Trainer itself.
func (r *Trainer) WithMaxExecutors(maxExecutors int) *Trainer {
	r.maxExecutors = maxExecutors
	return r
}

// WithInputsDynamicAxes configures the dynamic axes for the model inputs.
// Each slice in the axisNames parameter corresponds to an input parameter of the model graph.
//
// By marking an axis as dynamic, the computation graph will be compiled once with a symbolic size (e.g., shapes.DynamicDim)
// for that dimension. During subsequent executions, the actual size of the dynamic dimension is resolved dynamically
// from the shape of the execution inputs, avoiding expensive graph re-compilations for different input shapes.
//
// Dynamic axes configuration must be set before any training or evaluation step is executed, otherwise
// it will have no effect on already created executors.
//
// Example usage:
//
//	trainer := train.NewTrainer(backend, store, modelFn, lossFn, opt, nil, nil).
//		WithInputsDynamicAxes([]string{"batch", ""})
func (r *Trainer) WithInputsDynamicAxes(axisNames ...[]string) *Trainer {
	r.inputsDynamicAxes = axisNames
	return r
}

// WithLabelsDynamicAxes configures the dynamic axes for the model labels.
// Each slice in the axisNames parameter corresponds to a label parameter of the model graph.
//
// By marking an axis as dynamic, the computation graph will be compiled once with a symbolic size (e.g., shapes.DynamicDim)
// for that dimension. During subsequent executions, the actual size of the dynamic dimension is resolved dynamically
// from the shape of the execution inputs, avoiding expensive graph re-compilations for different input shapes.
//
// Dynamic axes configuration must be set before any training or evaluation step is executed, otherwise
// it will have no effect on already created executors.
//
// Example usage:
//
//	trainer := train.NewTrainer(backend, store, modelFn, lossFn, opt, nil, nil).
//		WithLabelsDynamicAxes([]string{"batch"})
func (r *Trainer) WithLabelsDynamicAxes(axisNames ...[]string) *Trainer {
	r.labelsDynamicAxes = axisNames
	return r
}

// TrainMetrics returns the train metrics objects (not the actual values just the objects
// that implement them).
func (r *Trainer) TrainMetrics() []metric.Interface { return r.trainMetrics }

// EvalMetrics returns the eval metrics objects: not the actual metric values, just the objects
// that implement them, holds their name and a default pretty-printing function.
func (r *Trainer) EvalMetrics() []metric.Interface { return r.evalMetrics }

// createExecutor (train or eval) for the given spec. Returns an error if it failed for
// any reason, including exceeding maxExecutors.
func (r *Trainer) createExecutor(spec any, inputsLen, labelsLen int,
	graphFn func(spec any, scope *model.Scope, inputs, labels []*graph.Node) (metrics []*graph.Node)) (
	*model.Exec, error) {
	numExecs := len(r.trainStepExecMap) + len(r.evalStepExecMap) +
		len(r.accumulateGradientsExecMap) + len(r.accumulateGradientsAndApplyExecMap) +
		len(r.batchNormStepExecMap)
	if numExecs > r.maxExecutors {
		return nil, errors.Errorf("Max number of executors reached: one is created for each "+
			"different value of `spec` returned by Dataset, triggering a different JIT-compiled "+
			"computation graph. Probably you want to limit the number of different datasets configuration "+
			"(spec) or shapes supported, or increase the allowed number of executors (see Train.WithMaxExecutors) "+
			" if this is what you want. Value of spec passed at this iteration: %+v", spec)
	}
	r.inputsAndLabelsLenPerSpec[spec] = [2]int{inputsLen, labelsLen}
	trainerName := "Trainer"
	if _, found := spec.(fmt.Stringer); found {
		trainerName = fmt.Sprintf("Trainer: spec=%s", spec)
	}
	exec, err := model.NewExec(r.backend, r.store.Store(),
		func(scope *model.Scope, inputsAndLabels []*graph.Node) (metrics []*graph.Node) {
			inputs := inputsAndLabels[:inputsLen]
			labels := inputsAndLabels[inputsLen:]
			return graphFn(spec, scope, inputs, labels)
		})
	if err != nil {
		return nil, errors.WithMessagef(err, "failed to create executor for spec %+v", spec)
	}

	var combinedAxes [][]string
	if len(r.inputsDynamicAxes) > 0 || len(r.labelsDynamicAxes) > 0 {
		combinedAxes = make([][]string, inputsLen+labelsLen)
		for i := 0; i < inputsLen; i++ {
			if i < len(r.inputsDynamicAxes) {
				combinedAxes[i] = r.inputsDynamicAxes[i]
			}
		}
		for i := 0; i < labelsLen; i++ {
			if i < len(r.labelsDynamicAxes) {
				combinedAxes[inputsLen+i] = r.labelsDynamicAxes[i]
			}
		}
	}
	if len(combinedAxes) > 0 {
		exec.WithDynamicAxes(combinedAxes...)
	}

	if r.deviceAssignment != nil {
		exec = exec.WithDeviceAssignment(r.deviceAssignment)
	}
	return exec.WithName(trainerName), nil
}

// lossFnScalarLoss calls `r.lossFn` and [ReduceAllMean] to a scalar.
// It assumes `r.lossFn != nil`.
func (r *Trainer) lossFnScalarLoss(_ *model.Scope, labels, predictions []*graph.Node) *graph.Node {
	loss := r.lossFn(labels, predictions)
	if !loss.Shape().IsScalar() {
		loss = graph.ReduceAllMean(loss)
	}
	return loss
}

// trainStepGraph builds the graph to train one step. It is called by the scope executor (`r.trainStepExecMap`)
// every time a graph needs to be built (typically for new batch sizes).
func (r *Trainer) trainStepGraph(spec any, scope *model.Scope, inputs, labels []*graph.Node) (metrics []*graph.Node) {
	g := inputs[0].Graph()
	scope.Store().SetTraining(g, true) // Some layers behave differently if in training.

	// AddMainLoss generated by the given lossFn.
	predictions := r.modelFn(scope, spec, inputs)
	if r.lossFn != nil {
		baseLoss := r.lossFnScalarLoss(scope, labels, predictions)
		AddMainLoss(baseLoss)
	}

	// Store total loss as a variable, so it can be used by metrics.
	loss := TotalLoss(g)
	if loss == nil {
		exceptions.Panicf(
			"no loss function defined (or it returned nil), and no loss set with AddMainLoss(), there is nothing to optimize!?",
		)
	}

	// Optimizer: it will create graph for gradient.
	r.optimizer.UpdateGraph(scope, g, loss)

	// Execute registered ScopeGraphFn hooks for current graph.
	ExecPerStepUpdateGraphFn(g)

	// Metrics updates. They include: batch loss, exponential moving average of the batch loss.
	if len(predictions) == 0 {
		// We create a zero prediction (same dtype as loss), because the metrics require something.
		predictions = []*graph.Node{graph.ScalarZero(g, loss.DType())}
	}
	metrics = r.metricsUpdatesGraph(scope, labels, predictions, r.trainMetrics)
	return
}

// callGraphFn for TrainStep or EvalStep makes sure the builds the arguments for execution,
// plus do standard checks on inputs and labels.
func (r *Trainer) callGraphFn(
	graphFn func(spec any, scope *model.Scope, inputs, labels []*graph.Node) (metrics []*graph.Node),
	graphType GraphType,
	execMap map[any]*model.Exec,
	spec any,
	inputs, labels []*tensors.Tensor,
) (metrics []*tensors.Tensor, err error) {
	if len(inputs) == 0 {
		return nil, errors.New("there are no inputs, at least one is required")
	}
	if lengths, found := r.inputsAndLabelsLenPerSpec[spec]; found {
		if len(inputs) != lengths[0] || len(labels) != lengths[1] {
			return nil, errors.Errorf("dataset yields inputs (%d) and labels (%d) with lengths different "+
				"than with previous call (%d and %d) for the given spec %+v", len(inputs), len(labels),
				lengths[0], lengths[1], spec)
		}
	}
	for ii, input := range inputs {
		if input == nil {
			return nil, errors.Errorf("inputs[%d] is nil!?", ii)
		}
	}

	// Create arguments as []any and run trainStepExecMap.Exec().
	numParams := len(inputs) + len(labels)
	inputsAndLabels := make([]any, 0, numParams)
	for _, t := range inputs {
		inputsAndLabels = append(inputsAndLabels, t)
	}
	for _, t := range labels {
		inputsAndLabels = append(inputsAndLabels, t)
	}

	// Get the executor for the graphType and input spec.
	exec, found := execMap[spec]
	if !found {
		exec, err = r.createExecutor(spec, len(inputs), len(labels), graphFn)
		if err != nil {
			return nil, err
		}
		execMap[spec] = exec
		for _, handler := range r.onExecCreationHandlers {
			handler(exec, graphType) // Call the handler for training.
		}
	}

	// Collect metrics:
	metrics, err = exec.Exec(inputsAndLabels...)
	if err != nil {
		return nil, errors.WithMessage(err, "failed to execute train/eval step")
	}
	if len(metrics) == 0 {
		return nil, errors.New("no metrics calculate metric in step")
	}
	return metrics, nil
}

// distributedCallGraphFn for DistributedTrainStep or DistributedEvalStep makes sure the builds the arguments for
// execution, plus do standard checks on inputs and labels.
//
// Notice that the returned metrics are not distributed.
func (r *Trainer) distributedCallGraphFn(
	strategy distributed.Strategy,
	deviceAssignment []compute.DeviceNum,
	graphFn func(spec any, scope *model.Scope, inputs, labels []*graph.Node) (metrics []*graph.Node),
	graphType GraphType,
	execMap map[any]*model.Exec,
	spec any,
	inputs, labels []*dtensor.Tensor,
) (metrics []*tensors.Tensor, err error) {
	if len(inputs) == 0 {
		return nil, errors.New("there are no inputs, at least one is required")
	}
	if lengths, found := r.inputsAndLabelsLenPerSpec[spec]; found {
		if len(inputs) != lengths[0] || len(labels) != lengths[1] {
			return nil, errors.Errorf("dataset yields inputs (%d) and labels (%d) with lengths different "+
				"than with previous call (%d and %d) for the given spec %+v", len(inputs), len(labels),
				lengths[0], lengths[1], spec)
		}
	}
	for ii, input := range inputs {
		if input == nil {
			return nil, errors.Errorf("inputs[%d] is nil!?", ii)
		}
	}

	// Create arguments as []any and run trainStepExecMap.Exec().
	numParams := len(inputs) + len(labels)
	inputsAndLabels := make([]any, 0, numParams)
	for _, t := range inputs {
		inputsAndLabels = append(inputsAndLabels, t)
	}
	for _, t := range labels {
		inputsAndLabels = append(inputsAndLabels, t)
	}

	// Get the executor for the graphType and input spec.
	exec, found := execMap[spec]
	if !found {
		// Set up of the executor and compilation of the computation graph: this happens only
		// once for each inputs/labels shape combination.
		exec, err = r.createExecutor(spec, len(inputs), len(labels), graphFn)
		if err != nil {
			return nil, err
		}

		// Find meshes and aggregate all input ShardingSpec.
		var meshes []*distributed.DeviceMesh
		inputShardingSpecs := make([]*distributed.ShardingSpec, 0, numParams)
		for _, inputAny := range inputsAndLabels {
			input := inputAny.(*dtensor.Tensor)
			shardingSpec := input.ShardingSpec()
			mesh := shardingSpec.Mesh
			if slices.Index(meshes, mesh) == -1 {
				meshes = append(meshes, mesh)
			}
			inputShardingSpecs = append(inputShardingSpecs, shardingSpec)
		}
		if len(meshes) == 0 {
			return nil, errors.New("missing a mesh definition from the inputs/labels (likely from a DistributedDataset)")
		}
		replicatedSpec := distributed.NewReplicatedShardingSpec(meshes[0])

		// Setup exec for distributed execution:
		switch strategy {
		case distributed.AutoSharding:
			exec = exec.AutoSharding(meshes...).
				WithInputShardingSpecs(inputShardingSpecs...).
				WithOutputShardingSpecs(replicatedSpec).
				WithDeviceAssignment(deviceAssignment)
		case distributed.SPMD:
			if len(meshes) > 1 {
				return nil, errors.Errorf("the distributed strategy SPMD only accepts one mesh for sharding the inputs, got %d",
					len(meshes))
			}
			exec = exec.SPMD(meshes[0]).
				WithInputShardingSpecs(inputShardingSpecs...).
				WithOutputShardingSpecs(replicatedSpec).
				WithDeviceAssignment(deviceAssignment)
		case distributed.None:
			return nil, errors.New("cannot do a distributed train/eval step if the strategy is None -- try distributed.AutoSharding?")
		}

		// Register new executor.
		execMap[spec] = exec
		for _, handler := range r.onExecCreationHandlers {
			handler(exec, graphType) // Call the handler for training.
		}
	}

	// Execute, it returns the distributed metrics:
	distributedMetrics, err := exec.DistributedExec(inputsAndLabels...)
	if err != nil {
		return nil, errors.WithMessage(err, "failed to execute train/eval step")
	}
	if len(distributedMetrics) == 0 {
		return nil, errors.New("no metrics calculate metric in step")
	}

	// Collect the metrics from the first device:
	metrics = make([]*tensors.Tensor, len(distributedMetrics))
	for i, distributedMetric := range distributedMetrics {
		metrics[i], err = distributedMetric.Shards()[0].LocalClone()
		if err != nil {
			return nil, errors.WithMessagef(err, "failed to clone metric %d from distributed metric", i)
		}
		err = distributedMetric.Finalize()
		if err != nil {
			return nil, errors.WithMessagef(err, "failed to finalize distributed metric %d", i)
		}
	}
	return metrics, nil
}

// ResetComputationGraphs can be used during training in between steps to force the recreation of the computation graphs.
//
// This is used if, for instance, the training has schedules where hyperparameters change (some variables are frozen)
// the computation graph needs to be updated accordingly.
//
// see Loop.OnStep to schedule
func (r *Trainer) ResetComputationGraphs() {
	for _, execMap := range []map[any]*model.Exec{r.trainStepExecMap, r.evalStepExecMap, r.batchNormStepExecMap,
		r.accumulateGradientsExecMap, r.accumulateGradientsAndApplyExecMap} {
		for _, e := range execMap {
			e.Finalize()
		}
		clear(execMap)
	}
}

// metricsUpdatesGraph creates the graph for a set of metrics.
func (r *Trainer) metricsUpdatesGraph(scope *model.Scope, labels, predictions []*graph.Node,
	metricsObjects []metric.Interface) (metrics []*graph.Node) {
	numMetrics := len(metricsObjects)
	metrics = make([]*graph.Node, 0, numMetrics)
	for _, m := range metricsObjects {
		// Pass a fresh Scope (at the same path) to each metric, so its visitedPaths is empty,
		// allowing multiple metrics to independently enter the "metrics" sub-scope.
		metricResult := m.UpdateGraph(scope, labels, predictions)
		metrics = append(metrics, metricResult)
	}
	return
}

// TrainStep runs one step and returns the metrics.
func (r *Trainer) TrainStep(spec any, inputs, labels []*tensors.Tensor) (metrics []*tensors.Tensor, err error) {
	if r.accumulateGradients {
		// Version that accumulate gradients.
		return r.trainStepWithAccumulateGradients(spec, inputs, labels)
	}
	return r.callGraphFn(r.trainStepGraph, TrainType, r.trainStepExecMap, spec, inputs, labels)
}

// DistributedTrainStep runs one step and returns the metrics, in a distributed fashion.
func (r *Trainer) DistributedTrainStep(strategy distributed.Strategy, deviceAssignment []compute.DeviceNum,
	spec any, inputs, labels []*dtensor.Tensor) (metrics []*tensors.Tensor, err error) {
	if r.accumulateGradients {
		// Version that accumulate gradients.
		return nil, errors.New("distributed training with gradient accumulation not implemented yet")
	}
	return r.distributedCallGraphFn(strategy, deviceAssignment, r.trainStepGraph, TrainType, r.trainStepExecMap, spec, inputs, labels)
}

// evalStepGraph builds the graph to eval one step. It is called by the scope executor (`r.evalStepExecMap`)
// every time a graph needs to be built (typically for new batch sizes).
func (r *Trainer) evalStepGraph(spec any, scope *model.Scope, inputs, labels []*graph.Node) (metrics []*graph.Node) {
	g := inputs[0].Graph()
	scope.Store().SetTraining(g, false) // Some layers behave differently in train/eval.

	predictions := r.modelFn(scope, spec, inputs)
	if r.lossFn != nil {
		baseLoss := r.lossFnScalarLoss(scope, labels, predictions)
		AddMainLoss(baseLoss)
	}

	// Get metrics and updates
	metrics = r.metricsUpdatesGraph(scope, labels, predictions, r.evalMetrics)
	return
}

// ResetTrainMetrics call Metrics.Reset on all train metrics. Usually called before a training session.
func (r *Trainer) ResetTrainMetrics() error {
	for _, m := range r.trainMetrics {
		err := exceptions.TryCatch[error](func() { m.Reset(r.store.RootScope()) })
		if err != nil {
			panic(errors.WithMessagef(err, "Eval() failed to reset metric %q", m.Name()))
		}
	}
	return nil
}

// EvalStep runs one eval step and returns the metrics, the first one being the mean loss.
func (r *Trainer) EvalStep(spec any, inputs, labels []*tensors.Tensor) (metrics []*tensors.Tensor, err error) {
	return r.callGraphFn(r.evalStepGraph, EvalType, r.evalStepExecMap, spec, inputs, labels)
}

// DistributedEvalStep runs one eval step and returns the metrics, in a distributed fashion.
func (r *Trainer) DistributedEvalStep(strategy distributed.Strategy, deviceAssignment []compute.DeviceNum,
	spec any, inputs, labels []*dtensor.Tensor) (metrics []*tensors.Tensor, err error) {
	return r.distributedCallGraphFn(strategy, deviceAssignment, r.evalStepGraph, EvalType, r.evalStepExecMap, spec, inputs, labels)
}

// resetEvalMetrics call Metrics.Reset on all eval metrics.
func (r *Trainer) resetEvalMetrics() error {
	for _, m := range r.evalMetrics {
		err := exceptions.TryCatch[error](func() { m.Reset(r.store.RootScope()) })
		if err != nil {
			return errors.WithMessagef(err, "Eval() failed to reset metric %q", m.Name())
		}
	}
	return nil
}

// Eval returns the computation of loss and metrics over the given dataset.
func (r *Trainer) Eval(ds Dataset) (lossAndMetrics []*tensors.Tensor, err error) {
	if distributedDS, ok := ds.(DistributedDataset); ok {
		return r.DistributedEval(distributedDS)
	}
	ds.Reset()
	err = r.resetEvalMetrics()
	if err != nil {
		return nil, err
	}
	count := 0
	finalizeInputs := finalizeYieldedTensors(ds)

	// Check for metrics with Go updates: these are update functions not written as a computation graph.
	goUpdateFns := make([]metric.UpdateGo, len(r.evalMetrics))
	for ii, m := range r.evalMetrics {
		if fn, ok := m.(metric.UpdateGo); ok {
			goUpdateFns[ii] = fn
		}
	}

	// Loop over dataset:
	for {
		spec, inputs, labels, err := ds.Yield()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, errors.Wrap(err, "dataset returned an error during Eval")
		}
		count++
		// Early free (not wait for the GC) of the results of previous batch.
		for _, t := range lossAndMetrics {
			err := t.FinalizeAll()
			if err != nil {
				return nil, errors.WithMessagef(err,
					"finalizing loss and metrics tensor of dataset %q after use in a distributed eval step",
					ds.Name())
			}
		}

		lossAndMetrics, err = r.EvalStep(spec, inputs, labels)
		if err != nil {
			return nil, errors.WithMessage(err, "EvalStep failed")
		}
		for i, goUpdateFn := range goUpdateFns {
			if goUpdateFn != nil {
				goUpdateFn.UpdateGo(lossAndMetrics[i])
			}
		}

		// Free inputs and labels after usage.
		if finalizeInputs {
			for sliceIdx, slice := range [][]*tensors.Tensor{inputs, labels} {
				for i, t := range slice {
					err := t.FinalizeAll()
					if err != nil {
						return nil, errors.WithMessagef(
							err, "finalizing %s tensor #%d of dataset %q after use in a distributed eval step",
							yieldInputTypeNames[sliceIdx], i, ds.Name())
					}
				}
			}
		}
	}
	if count == 0 {
		return nil, errors.New("evaluation dataset yielded no batches, no data to evaluate")
	}

	// Read out the go-generate metrics:
	for i, goUpdateFn := range goUpdateFns {
		if goUpdateFn != nil {
			lossAndMetrics[i] = goUpdateFn.ReadGo()
		}
	}
	return lossAndMetrics, nil
}

// DistributedEval returns the computation of loss and metrics over the given distributed dataset.
func (r *Trainer) DistributedEval(ds DistributedDataset) (lossAndMetrics []*tensors.Tensor, err error) {
	ds.Reset()
	err = r.resetEvalMetrics()
	if err != nil {
		return nil, err
	}
	count := 0
	finalizeInputs := finalizeYieldedTensors(ds)
	strategy := ds.Strategy()
	deviceAssignment := ds.DeviceAssignment()

	// Check for metrics with Go updates: these are update functions not written as a computation graph.
	goUpdateFns := make([]metric.UpdateGo, len(r.evalMetrics))
	for ii, m := range r.evalMetrics {
		if fn, ok := m.(metric.UpdateGo); ok {
			goUpdateFns[ii] = fn
		}
	}

	// Loop over dataset:
	for {
		spec, inputs, labels, err := ds.DistributedYield()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, errors.Wrap(err, "dataset returned an error during DistributedEval")
		}
		count++
		// Early free (not wait for the GC) of the results of previous batch.
		for _, t := range lossAndMetrics {
			err := t.FinalizeAll()
			if err != nil {
				return nil, errors.WithMessagef(err,
					"finalizing loss and metrics tensor of dataset %q after use in a distributed eval step",
					ds.Name())
			}
		}

		lossAndMetrics, err = r.DistributedEvalStep(strategy, deviceAssignment, spec, inputs, labels)
		if err != nil {
			return nil, errors.WithMessage(err, "DistributedEvalStep failed")
		}
		for i, goUpdateFn := range goUpdateFns {
			if goUpdateFn != nil {
				goUpdateFn.UpdateGo(lossAndMetrics[i])
			}
		}

		// Free inputs and labels after usage.
		if finalizeInputs {
			for sliceIdx, slice := range [][]*dtensor.Tensor{inputs, labels} {
				for i, t := range slice {
					err := t.FinalizeAll()
					if err != nil {
						return nil, errors.WithMessagef(
							err, "finalizing %s distributed tensor #%d of dataset %q after use in a distributed eval step",
							yieldInputTypeNames[sliceIdx], i, ds.Name())
					}
				}
			}
		}
	}
	if count == 0 {
		return nil, errors.New("evaluation dataset yielded no batches, no data to evaluate")
	}

	// Read out the go-generated metrics:
	for i, goUpdateFn := range goUpdateFns {
		if goUpdateFn != nil {
			lossAndMetrics[i] = goUpdateFn.ReadGo()
		}
	}
	return lossAndMetrics, nil
}

// Metrics return list of registered eval metrics, including the loss metric that is added automatically.
func (r *Trainer) Metrics() []metric.Interface {
	return r.evalMetrics
}

// GlobalStep is an alias for optimizer.GetGlobalStep using Trainer.Scope().
func (r *Trainer) GlobalStep() int64 {
	return optimizer.GetGlobalStep(r.store)
}

// OnExecFn is a handler that can be called when executors are created.
type OnExecFn func(exec *model.Exec, graphType GraphType)

// OnExecCreation registers a handler to be called each time an executor (`model.Exec`) is created by the trainer.
func (r *Trainer) OnExecCreation(handler OnExecFn) {
	r.onExecCreationHandlers = append(r.onExecCreationHandlers, handler)
}

// AddMainLoss adds the given scalar loss to the trainer's Store as a main loss for the current graph.
// If another main loss has already been added, they are summed.
//
// This is a global value for the Store, not scoped.
func AddMainLoss(theLoss *graph.Node) {
	g := theLoss.Graph()
	if !theLoss.Shape().IsScalar() {
		theLoss = graph.ReduceAllMean(theLoss)
	}

	fullPath := model.JoinPath(TrainerAbsoluteScope, TrainerMainLossGraphParamKey)
	currentLoss, found := model.GetGraphParam(g, fullPath)
	if found {
		theLoss = graph.Add(theLoss, currentLoss.(*graph.Node))
	}
	model.SetGraphParam(g, fullPath, theLoss)
}

// AddRegularizationLoss adds the given scalar loss to the trainer's Store as a regularization loss for the current graph.
// If another regularization loss has already been added, they are summed.
//
// This is a global value for the Store, not scoped.
func AddRegularizationLoss(theLoss *graph.Node) {
	g := theLoss.Graph()
	if !theLoss.Shape().IsScalar() {
		theLoss = graph.ReduceAllMean(theLoss)
	}

	fullPath := model.JoinPath(TrainerAbsoluteScope, TrainerRegularizationLossGraphParamKey)
	currentLoss, found := model.GetGraphParam(g, fullPath)
	if found {
		theLoss = graph.Add(theLoss, currentLoss.(*graph.Node))
	}
	model.SetGraphParam(g, fullPath, theLoss)
}

// AddLoss adds the given scalar loss to the trainer's Store for the current graph.
//
// Deprecated: use AddMainLoss for main losses, or AddRegularizationLoss for regularization losses.
// This function maps to AddRegularizationLoss to preserve backward compatibility.
func AddLoss(theLoss *graph.Node) {
	AddRegularizationLoss(theLoss)
}

// GetMainLoss returns the sum of all main loss terms added with AddMainLoss(), or nil if none was set.
//
// This is a global value for the Store, not scoped.
func GetMainLoss(g *graph.Graph) (loss *graph.Node) {
	fullPath := model.JoinPath(TrainerAbsoluteScope, TrainerMainLossGraphParamKey)
	lossAny, found := model.GetGraphParam(g, fullPath)
	if !found {
		return nil
	}
	return lossAny.(*graph.Node)
}

// GetRegularizationLoss returns the sum of all regularization loss terms added with AddRegularizationLoss() (or the deprecated AddLoss()), or nil if none was set.
//
// This is a global value for the Store, not scoped.
func GetRegularizationLoss(g *graph.Graph) (loss *graph.Node) {
	fullPath := model.JoinPath(TrainerAbsoluteScope, TrainerRegularizationLossGraphParamKey)
	lossAny, found := model.GetGraphParam(g, fullPath)
	if !found {
		return nil
	}
	return lossAny.(*graph.Node)
}

// TotalLoss returns the sum of all main and regularization loss terms, or nil if none was set.
//
// This is a global value for the Store, not scoped.
func TotalLoss(g *graph.Graph) (loss *graph.Node) {
	mainLoss := GetMainLoss(g)
	regLoss := GetRegularizationLoss(g)
	if mainLoss == nil {
		return regLoss
	}
	if regLoss == nil {
		return mainLoss
	}
	return graph.Add(mainLoss, regLoss)
}

// GetLosses returns the sum of all main and regularization loss terms, or nil if none was set.
//
// Deprecated: use TotalLoss instead.
func GetLosses(g *graph.Graph) (loss *graph.Node) {
	return TotalLoss(g)
}

// SetLossNoRegularization saves the given loss value as the current main loss for this graph, discarding any previously set main losses.
//
// Deprecated: use AddMainLoss instead.
func SetLossNoRegularization(theLoss *graph.Node) {
	g := theLoss.Graph()
	if !theLoss.Shape().IsScalar() {
		theLoss = graph.ReduceAllMean(theLoss)
	}
	fullPath := model.JoinPath(TrainerAbsoluteScope, TrainerMainLossGraphParamKey)
	model.SetGraphParam(g, fullPath, theLoss)
}

// GetLossNoRegularization returns the loss of the model not including regularization.
//
// Deprecated: use GetMainLoss instead.
func GetLossNoRegularization(g *graph.Graph) (loss *graph.Node) {
	return GetMainLoss(g)
}

// ModelGraphFn is a generic graph building function that takes a model scope (which points to its [model.Store]).
type ModelGraphFn func(scope *model.Scope, g *graph.Graph)

// AddPerStepUpdateGraphFn registers the given function fn to be executed at every training step.
func AddPerStepUpdateGraphFn(scope *model.Scope, g *graph.Graph, fn ModelGraphFn) {
	scope.SetGraphParam(g, TrainerPerStepUpdateGraphFnParamKey, fn)
}

// ExecPerStepUpdateGraphFn executes all registered "per-step update functions".
//
// The Store object will be read from the Graph.
func ExecPerStepUpdateGraphFn(g *graph.Graph) {
	store := model.GetStore(g)
	if store == nil {
		panic(errors.Errorf("the current graph does not have an associated model.Store; to get one, you need to create the graph using a [model.Exec] (see [model.NewExec])"))
	}
	for p := range store.IterGraphParams(g) {
		if p.Key != TrainerPerStepUpdateGraphFnParamKey {
			continue
		}
		if fn, ok := p.Value.(ModelGraphFn); ok {
			fn(store.Scope(p.Scope), g)
		}
	}
}
