package engine

import (
	"fmt"

	. "github.com/gomlx/gomlx/pkg/core/graph"
	"github.com/gomlx/gomlx/pkg/core/tensors"
	mlctx "github.com/gomlx/gomlx/pkg/ml/context"
	"github.com/gomlx/gomlx/pkg/ml/decode"
)

// SpeculativeConfig configures speculative decoding.
type SpeculativeConfig struct {
	// DraftModelFn is the small, fast model used to generate candidate tokens.
	DraftModelFn decode.BatchedModelFn

	// NumSpecTokens is the number of speculative tokens to generate per step.
	// The draft model generates this many candidates, then the main model
	// verifies them all in one forward pass.
	// Default: 4.
	NumSpecTokens int
}

// speculativeState holds per-step speculative decoding state.
type speculativeState struct {
	// draftTokens are the candidate tokens generated by the draft model.
	draftTokens []int32

	// draftPositions records at what position each draft token was generated.
	draftPositions []int

	// accepted tracks how many draft tokens were accepted by verification.
	accepted int
}

// speculativeDecode generates N candidate tokens with the draft model,
// then verifies them with the main model in one batched forward pass.
//
// Returns the verified tokens (may be fewer than N if the main model
// disagrees with the draft).
func (e *Engine) speculativeDecode(req *engineRequest) error {
	if e.specConfig == nil {
		return fmt.Errorf("speculative decoding not configured")
	}

	numSpec := e.specConfig.NumSpecTokens
	if numSpec <= 0 {
		numSpec = 4
	}

	// Phase 1: Generate N candidate tokens with the draft model.
	state := &speculativeState{
		draftTokens:    make([]int32, 0, numSpec),
		draftPositions: make([]int, 0, numSpec),
	}

	currentToken := req.generatedTokens[len(req.generatedTokens)-1]
	currentPos := req.position

	for range numSpec {
		// Build single-token input for draft model.
		tokenTensor := tensors.FromValue([][]int32{{currentToken}})
		posTensor := tensors.FromValue([]int32{int32(currentPos)})

		// Execute draft model (uses same executor caching as main model).
		exec, err := e.getDraftExec(1)
		if err != nil {
			// Fall back to normal single-token decode.
			return e.decodeOneTokenBatched(req)
		}

		outputs, err := exec.Exec(tokenTensor, posTensor)
		if err != nil {
			return e.decodeOneTokenBatched(req)
		}

		// CPU-side greedy sample from draft logits.
		logits := outputs[0].Value().([][]float32)[0]
		nextToken := greedySample(logits)

		state.draftTokens = append(state.draftTokens, nextToken)
		state.draftPositions = append(state.draftPositions, currentPos)

		currentToken = nextToken
		currentPos++
	}

	// Phase 2: Verify all candidates with the main model in one forward pass.
	// Build verification input: [1, numSpec+1] — original token + all draft tokens.
	//
	// This is a prefill-style forward pass: positions is [1] containing the
	// starting absolute position. The model processes the full token sequence
	// starting at that position, producing logits for each position in the
	// sequence. mainLogits[i] contains logits predicting the token at position
	// req.position + i + 1 (i.e., the token after the i-th input token).
	verifyTokens := make([][]int32, 1)
	verifyTokens[0] = make([]int32, numSpec+1)
	verifyTokens[0][0] = req.generatedTokens[len(req.generatedTokens)-1]
	copy(verifyTokens[0][1:], state.draftTokens)

	verifyTensor := tensors.FromValue(verifyTokens)
	verifyPos := tensors.FromValue([]int32{int32(req.position)})

	// Use the verify executor which returns all-position logits.
	verifyExec, err := e.getVerifyExec()
	if err != nil {
		return e.decodeOneTokenBatched(req)
	}

	outputs, err := verifyExec.Exec(verifyTensor, verifyPos)
	if err != nil {
		return e.decodeOneTokenBatched(req)
	}

	// Compare main model's predictions with draft tokens.
	// mainLogits: [numSpec+1, vocabSize] — logits for each position.
	mainLogits := outputs[0].Value().([][]float32)

	state.accepted = 0
	for i := range numSpec {
		mainToken := greedySample(mainLogits[i])
		if mainToken == state.draftTokens[i] {
			state.accepted++
		} else {
			// First disagreement: accept main model's token instead.
			state.draftTokens[i] = mainToken
			state.accepted = i + 1
			break
		}
	}

	// If all draft tokens were accepted, also take the main model's
	// next prediction (the token after the last draft token).
	if state.accepted == numSpec {
		bonusToken := greedySample(mainLogits[numSpec])
		state.draftTokens = append(state.draftTokens, bonusToken)
		state.accepted++
	}

	// Stream accepted tokens.
	for i := range state.accepted {
		token := state.draftTokens[i]
		req.position++
		req.generatedTokens = append(req.generatedTokens, token)
		e.streamToken(req, token)
		if req.eosReached || len(req.generatedTokens) >= req.opts.MaxNewTokens {
			e.finishRequest(req, nil)
			return nil
		}
	}

	return nil
}

// decodeOneTokenBatched is a fallback single-token decode for batched mode.
func (e *Engine) decodeOneTokenBatched(req *engineRequest) error {
	exec, err := e.getBatchedDecodeExec(1)
	if err != nil {
		e.finishRequest(req, fmt.Errorf("get decode exec: %w", err))
		return nil
	}

	prevToken := req.generatedTokens[len(req.generatedTokens)-1]
	tokenTensor := tensors.FromValue([][]int32{{prevToken}})
	posTensor := tensors.FromValue([]int32{int32(req.position)})

	outputs, err := exec.Exec(tokenTensor, posTensor)
	if err != nil {
		e.finishRequest(req, fmt.Errorf("batched decode: %w", err))
		return nil
	}

	sampledTokens := outputs[0].Value().([]int32)
	nextToken := sampledTokens[0]

	req.position++
	req.generatedTokens = append(req.generatedTokens, nextToken)
	e.streamToken(req, nextToken)
	e.checkAndFinish(req)

	return nil
}

// getDraftExec returns a cached executor for the draft model.
// Returns logits [1, vocabSize] (last-token extracted, batch-1).
func (e *Engine) getDraftExec(paddedBatch int) (*mlctx.Exec, error) {
	if e.draftExecCache == nil {
		e.draftExecCache = make(map[int]*mlctx.Exec)
	}

	if exec, ok := e.draftExecCache[paddedBatch]; ok {
		return exec, nil
	}

	exec, err := mlctx.NewExec(e.backend, e.modelCtx.Reuse(),
		func(ctx *mlctx.Context, tokens, positions *Node) *Node {
			logits := e.specConfig.DraftModelFn(ctx, tokens, positions)
			// [batchSize, seqLen, vocab] → [batchSize, vocab]
			lastLogits := Slice(logits, AxisRange(), AxisElem(-1), AxisRange())
			lastLogits = Squeeze(lastLogits, 1)
			return lastLogits
		},
	)
	if err != nil {
		return nil, err
	}
	e.draftExecCache[paddedBatch] = exec
	return exec, nil
}

// getVerifyExec returns a cached executor for speculative verification.
// Takes [1, seqLen] tokens and [1] positions (starting absolute position),
// returns logits [seqLen, vocabSize] for ALL positions (not just the last one),
// with batch dimension squeezed. This is a prefill-style pass: the model
// processes the full sequence starting at the given position, so logits[i]
// predicts the token at position start + i + 1.
func (e *Engine) getVerifyExec() (*mlctx.Exec, error) {
	if e.verifyExec != nil {
		return e.verifyExec, nil
	}

	var err error
	e.verifyExec, err = mlctx.NewExec(e.backend, e.modelCtx.Reuse(),
		func(ctx *mlctx.Context, tokens *Node, positions *Node) *Node {
			logits := e.batchedFn(ctx, tokens, positions)
			// [1, seqLen, vocab] → [seqLen, vocab]
			return Squeeze(logits, 0)
		},
	)
	return e.verifyExec, err
}
