load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Used for building rules for .tar.gz files.
http_archive(
    name = "rules_pkg",
    sha256 = "335632735e625d408870ec3e361e192e99ef7462315caa887417f4d88c4c8fb8",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.9.0/rules_pkg-0.9.0.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.9.0/rules_pkg-0.9.0.tar.gz",
    ],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

# Bazel Skylib, required by llvm.
SKYLIB_VERSION = "1.3.0"

http_archive(
    name = "bazel_skylib",
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/{version}/bazel-skylib-{version}.tar.gz".format(version = SKYLIB_VERSION),
        "https://github.com/bazelbuild/bazel-skylib/releases/download/{version}/bazel-skylib-{version}.tar.gz".format(version = SKYLIB_VERSION),
    ],
)

# OpenXLA XLA: no releases yet, so we choose a specific commit version.
# Version should match the one in bazel.sh.
# Notice bazel.sh scrape the line below for the OpenXLA version, the format
# of the line should remain the same (the hash in between quotes), or bazel.sh
# must be changed accordingly.
OPENXLA_XLA_COMMIT_HASH = "0d9a1dbc2b02a316afbae3e3c9b4083dc16b894b"  # From 2023-03-30

http_archive(
    name = "xla",
    sha256 = "c86b68ce16b08ba1287c641b9790f5ba7944ebbfe7218710f11827c2a65569f4",
    strip_prefix = "xla-" + OPENXLA_XLA_COMMIT_HASH,
    urls = [
        "https://github.com/openxla/xla/archive/{hash}.zip".format(hash = OPENXLA_XLA_COMMIT_HASH),
    ],
)

#http_archive(
#    name = "org_tensorflow",
#    add_prefix = "tensorflow",
#    sha256 = "af0584df1a4e28763c32c218b39f8c4f3784fabb6a8859b00c02d743864dc191",
#    strip_prefix = "tensorflow-2.12.0",
#    urls = [
#        "https://github.com/tensorflow/tensorflow/archive/v2.12.0.zip",
#    ],
#)

# Create @tsl repository.
load("@xla//third_party:repo.bzl", "tf_vendored")

tf_vendored(
    name = "tsl",
    relpath = "third_party/tsl",
)

# Initialize the XLA repository and all dependencies.
#
# The cascade of load() statements and xla_workspace?() calls works around the
# restriction that load() statements need to be at the top of .bzl files.
# E.g. we can not retrieve a new repository with http_archive and then load()
# a macro from that repository in the same file.
load("@xla//:workspace4.bzl", "xla_workspace4")

xla_workspace4()

load("@xla//:workspace3.bzl", "xla_workspace3")

xla_workspace3()

load("@xla//:workspace2.bzl", "xla_workspace2")

xla_workspace2()

## Make @local_config_cuda workspace available.
#load("@xla//third_party/gpus:cuda_configure.bzl", "cuda_configure")

load("@xla//:workspace1.bzl", "xla_workspace1")

xla_workspace1()

load("@xla//:workspace0.bzl", "xla_workspace0")

xla_workspace0()
