package main

import (
	"fmt"
	"github.com/janpfeifer/must"
	"os"
	"os/exec"
	"text/template"
)

type DTypeInfo struct {
	DType, GoType string
}

type DispatcherInfo struct {
	Dispatcher, Generic string
	DTypes              []DTypeInfo
}

var (
	// data lists the dispatchers to include, their generic function and with which set of dtypes to support.
	data = []DispatcherInfo{
		{"dispatchMutableBytes", "mutableBytesGeneric", makeDTypes(true, true, true, true, true)},
		{"dispatchDotGeneral", "execNormalizedDotGeneralGeneric", makeDTypes(true, true, true, false, false)},
		{"dispatchWhere", "execWhereGeneric", makeDTypes(true, true, true, true, true)},
		{"dispatchReduceMax", "execReduceMaxGeneric", makeDTypes(true, true, true, false, false)},
		{"dispatchReduceMin", "execReduceMinGeneric", makeDTypes(true, true, true, false, false)},
		{"dispatchReduceSum", "execReduceSumGeneric", makeDTypes(true, true, true, false, false)},
		{"dispatchReduceProduct", "execReduceProductGeneric", makeDTypes(true, true, true, false, false)},
		{"dispatchTranspose", "execTransposeGeneric", makeDTypes(true, true, true, true, true)},
		{"dispatchBroadcast", "execBroadcastGeneric", makeDTypes(true, true, true, true, true)},
		{"dispatchBroadcastInDim", "execBroadcastInDimGeneric", makeDTypes(true, true, true, true, true)},
		{"dispatchIota", "execIotaGeneric", makeDTypes(true, true, true, false, false)},
		{"dispatchGather", "execGatherGeneric", makeDTypes(true, true, false, false, false)},
	}
	fileName = "gen_register_dispatchers.go"
)

func makeDTypes(ints, uints, floats, bfloat16, boolean bool) []DTypeInfo {
	dtypes := make([]DTypeInfo, 0, 32)
	if ints {
		dtypes = append(dtypes,
			DTypeInfo{"Int8", "int8"},
			DTypeInfo{"Int16", "int16"},
			DTypeInfo{"Int32", "int32"},
			DTypeInfo{"Int64", "int64"},
		)
	}
	if uints {
		dtypes = append(dtypes,
			DTypeInfo{"Uint8", "uint8"},
			DTypeInfo{"Uint16", "uint16"},
			DTypeInfo{"Uint32", "uint32"},
			DTypeInfo{"Uint64", "uint64"},
		)
	}
	if floats {
		dtypes = append(dtypes,
			DTypeInfo{"Float32", "float32"},
			DTypeInfo{"Float64", "float64"},
		)
	}
	if bfloat16 {
		dtypes = append(dtypes,
			DTypeInfo{"BFloat16", "bfloat16.BFloat16"},
		)
	}
	if boolean {
		dtypes = append(dtypes,
			DTypeInfo{"Bool", "bool"},
		)
	}
	return dtypes
}

func main() {
	registerTemplate := template.Must(
		template.
			New(fileName).
			Parse(

				`/***** File generated by ./internal/cmd/simplego_dispatcher. Don't edit it directly. *****/

package simplego

import (
	"github.com/gomlx/gopjrt/dtypes"
	"github.com/gomlx/gopjrt/dtypes/bfloat16"
)


func init() { 
{{- range .}}

	// {{.Dispatcher}}
{{- $dispatcher := .Dispatcher }}
{{- $generic := .Generic }}
{{- range .DTypes }}
	{{$dispatcher}}.RegisterIfNotSet(dtypes.{{.DType}}, {{$generic}}[{{.GoType}}])
{{- end }}
{{- end }}
}	
`))

	f := must.M1(os.Create(fileName))
	must.M(registerTemplate.Execute(f, data))
	must.M(f.Close())

	cmd := exec.Command("gofmt", "-w", fileName)
	fmt.Printf("\t%s\n", cmd)
	must.M(cmd.Run())
	fmt.Printf("\t\tgenerated %q\n", fileName)

}
