// Code generated by "stringer -type FFTType -trimprefix=FFT"; DO NOT EDIT.

package backends

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FFTForward-0]
	_ = x[FFTInverse-1]
	_ = x[FFTForwardReal-2]
	_ = x[FFTInverseReal-3]
}

const _FFTType_name = "ForwardInverseForwardRealInverseReal"

var _FFTType_index = [...]uint8{0, 7, 14, 25, 36}

func (i FFTType) String() string {
	if i < 0 || i >= FFTType(len(_FFTType_index)-1) {
		return "FFTType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FFTType_name[_FFTType_index[i]:_FFTType_index[i+1]]
}
