// Code generated by "stringer -type ReduceOpType -trimprefix=ReduceOp"; DO NOT EDIT.

package backends

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReduceOpUndefined-0]
	_ = x[ReduceOpSum-1]
	_ = x[ReduceOpProduct-2]
	_ = x[ReduceOpMax-3]
	_ = x[ReduceOpMin-4]
}

const _ReduceOpType_name = "UndefinedSumProductMaxMin"

var _ReduceOpType_index = [...]uint8{0, 9, 12, 19, 22, 25}

func (i ReduceOpType) String() string {
	if i < 0 || i >= ReduceOpType(len(_ReduceOpType_index)-1) {
		return "ReduceOpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReduceOpType_name[_ReduceOpType_index[i]:_ReduceOpType_index[i+1]]
}
