// Code generated by "stringer -type=NodeType node.go"; DO NOT EDIT.

package xla

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidNode-0]
	_ = x[ConstantNode-1]
	_ = x[IotaNode-2]
	_ = x[ParameterNode-3]
	_ = x[ConvertTypeNode-4]
	_ = x[WhereNode-5]
	_ = x[TupleNode-6]
	_ = x[GetTupleElementNode-7]
	_ = x[ReshapeNode-8]
	_ = x[BroadcastNode-9]
	_ = x[BroadcastInDimNode-10]
	_ = x[ReduceSumNode-11]
	_ = x[ReduceMaxNode-12]
	_ = x[ReduceMultiplyNode-13]
	_ = x[SliceNode-14]
	_ = x[PadNode-15]
	_ = x[GatherNode-16]
	_ = x[ScatterNode-17]
	_ = x[ConcatenateNode-18]
	_ = x[ConvGeneralDilatedNode-19]
	_ = x[ReverseNode-20]
	_ = x[TransposeNode-21]
	_ = x[ReduceWindowNode-22]
	_ = x[SelectAndScatterNode-23]
	_ = x[BatchNormTrainingNode-24]
	_ = x[BatchNormInferenceNode-25]
	_ = x[BatchNormGradNode-26]
	_ = x[DotGeneralNode-27]
	_ = x[ArgMinMaxNode-28]
	_ = x[AbsNode-29]
	_ = x[NegNode-30]
	_ = x[ExpNode-31]
	_ = x[Expm1Node-32]
	_ = x[FloorNode-33]
	_ = x[CeilNode-34]
	_ = x[RoundNode-35]
	_ = x[LogNode-36]
	_ = x[Log1pNode-37]
	_ = x[LogicalNotNode-38]
	_ = x[LogisticNode-39]
	_ = x[SignNode-40]
	_ = x[ClzNode-41]
	_ = x[CosNode-42]
	_ = x[SinNode-43]
	_ = x[TanhNode-44]
	_ = x[SqrtNode-45]
	_ = x[RsqrtNode-46]
	_ = x[AddNode-47]
	_ = x[MulNode-48]
	_ = x[SubNode-49]
	_ = x[DivNode-50]
	_ = x[RemNode-51]
	_ = x[AndNode-52]
	_ = x[OrNode-53]
	_ = x[XorNode-54]
	_ = x[DotNode-55]
	_ = x[MinNode-56]
	_ = x[MaxNode-57]
	_ = x[PowNode-58]
	_ = x[EqualNode-59]
	_ = x[NotEqualNode-60]
	_ = x[GreaterOrEqualNode-61]
	_ = x[GreaterThanNode-62]
	_ = x[LessOrEqualNode-63]
	_ = x[LessThanNode-64]
	_ = x[EqualTotalOrderNode-65]
	_ = x[NotEqualTotalOrderNode-66]
	_ = x[GreaterOrEqualTotalOrderNode-67]
	_ = x[GreaterThanTotalOrderNode-68]
	_ = x[LessOrEqualTotalOrderNode-69]
	_ = x[LessThanTotalOrderNode-70]
	_ = x[RngBitGeneratorNode-71]
	_ = x[RngNormalNode-72]
	_ = x[RngUniformNode-73]
	_ = x[FftNode-74]
}

const _NodeType_name = "InvalidNodeConstantNodeIotaNodeParameterNodeConvertTypeNodeWhereNodeTupleNodeGetTupleElementNodeReshapeNodeBroadcastNodeBroadcastInDimNodeReduceSumNodeReduceMaxNodeReduceMultiplyNodeSliceNodePadNodeGatherNodeScatterNodeConcatenateNodeConvGeneralDilatedNodeReverseNodeTransposeNodeReduceWindowNodeSelectAndScatterNodeBatchNormTrainingNodeBatchNormInferenceNodeBatchNormGradNodeDotGeneralNodeArgMinMaxNodeAbsNodeNegNodeExpNodeExpm1NodeFloorNodeCeilNodeRoundNodeLogNodeLog1pNodeLogicalNotNodeLogisticNodeSignNodeClzNodeCosNodeSinNodeTanhNodeSqrtNodeRsqrtNodeAddNodeMulNodeSubNodeDivNodeRemNodeAndNodeOrNodeXorNodeDotNodeMinNodeMaxNodePowNodeEqualNodeNotEqualNodeGreaterOrEqualNodeGreaterThanNodeLessOrEqualNodeLessThanNodeEqualTotalOrderNodeNotEqualTotalOrderNodeGreaterOrEqualTotalOrderNodeGreaterThanTotalOrderNodeLessOrEqualTotalOrderNodeLessThanTotalOrderNodeRngBitGeneratorNodeRngNormalNodeRngUniformNodeFftNode"

var _NodeType_index = [...]uint16{0, 11, 23, 31, 44, 59, 68, 77, 96, 107, 120, 138, 151, 164, 182, 191, 198, 208, 219, 234, 256, 267, 280, 296, 316, 337, 359, 376, 390, 403, 410, 417, 424, 433, 442, 450, 459, 466, 475, 489, 501, 509, 516, 523, 530, 538, 546, 555, 562, 569, 576, 583, 590, 597, 603, 610, 617, 624, 631, 638, 647, 659, 677, 692, 707, 719, 738, 760, 788, 813, 838, 860, 879, 892, 906, 913}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
