// Code generated by "stringer -type=RandomAlgorithm node.go"; DO NOT EDIT.

package xla

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RngDefault-0]
	_ = x[RngThreeFry-1]
	_ = x[RngPhilox-2]
}

const _RandomAlgorithm_name = "RngDefaultRngThreeFryRngPhilox"

var _RandomAlgorithm_index = [...]uint8{0, 10, 21, 30}

func (i RandomAlgorithm) String() string {
	if i < 0 || i >= RandomAlgorithm(len(_RandomAlgorithm_index)-1) {
		return "RandomAlgorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RandomAlgorithm_name[_RandomAlgorithm_index[i]:_RandomAlgorithm_index[i+1]]
}
