// Copyright 2023-2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

// constraint_generator prints out various lists of constraints used by generics,
// which can then be copy&pasted into the code.
// It is an internal tool, meant to be used by developers of GoMLX.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path"
	"strings"

	"github.com/gomlx/gomlx/internal/must"
	"k8s.io/klog/v2"
)

var baseTypes = []string{
	"bool", "float32", "float64", "int", "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64", "complex64", "complex128",
	"bfloat16.BFloat16", "float16.Float16"}

const SliceLevels = 5

const outputFile = "gen_constraints.go"

func TensorSlicesConstraints(w io.Writer) {
	count := 0
	for slices := range SliceLevels {
		fmt.Fprintf(w, "\t")
		for idxType, t := range baseTypes {
			if idxType > 0 {
				fmt.Fprint(w, " | ")
			}
			for ii := 0; ii < slices; ii++ {
				fmt.Fprint(w, "[]")
			}
			fmt.Fprint(w, t)
			count += 1
		}
		if slices < SliceLevels-1 {
			fmt.Fprintf(w, " |")
		}
		fmt.Fprintln(w)
	}
}

func GraphExecFnConstraints(w io.Writer, withScope bool) {
	p := ""
	if withScope {
		p = "graph."
	}
	possibleInputs := []string{"*" + p + "Graph", "[]*" + p + "Node", "*" + p + "Graph, []*" + p + "Node"}
	nodesParams := "*" + p + "Node"
	for range 6 {
		possibleInputs = append(possibleInputs, nodesParams)
		nodesParams = nodesParams + ", *" + p + "Node"
	}
	
	type outputConfig struct {
		name   string
		output string
	}
	possibleOutputs := []outputConfig{}
	if withScope {
		possibleOutputs = append(possibleOutputs, outputConfig{"ZeroOutputs", ""})
	}
	possibleOutputs = append(possibleOutputs,
		outputConfig{"OneOutput", "*" + p + "Node"},
		outputConfig{"TwoOutputs", "(*" + p + "Node, *" + p + "Node)"},
		outputConfig{"ThreeOutputs", "(*" + p + "Node, *" + p + "Node, *" + p + "Node)"},
		outputConfig{"SliceOutputs", "[]*" + p + "Node"},
	)
	var contextInput string
	if withScope {
		contextInput = "*Scope, "
	}
	
	var interfaceNames []string
	for _, outConfig := range possibleOutputs {
		interfaceName := fmt.Sprintf("ExecGraphFn%s", outConfig.name)
		interfaceNames = append(interfaceNames, interfaceName)
		fmt.Fprintf(w, "type %s interface {\n", interfaceName)
		var parts []string
		outputs := outConfig.output
		if outputs != "" {
			outputs = " " + outputs
		}
		for _, inputs := range possibleInputs {
			parts = append(parts, fmt.Sprintf("\tfunc (%s%s)%s", contextInput, inputs, outputs))
		}
		fmt.Fprintf(w, "%s\n}\n\n", strings.Join(parts, " |\n"))
	}
	fmt.Fprintf(w, "type ExecGraphFn interface {\n\t%s\n}\n", strings.Join(interfaceNames, " | "))
}

var (
	flagModel   = flag.Bool("model", false, "Generate constraints for the model package.")
	flagGraph   = flag.Bool("graph", false, "Generate constraints for the graph package.")
	flagTensors = flag.Bool("tensors", false, "Generate constraints for the tensors package.")
)

func main() {
	flag.Parse()

	numFlags := 0
	if *flagModel {
		numFlags++
	}
	if *flagGraph {
		numFlags++
	}
	if *flagTensors {
		numFlags++
	}
	if numFlags != 1 {
		klog.Exitf("Please specify exactly one of -context, -graph, or -tensors flag")
	}

	outputPath := path.Join(must.M1(os.Getwd()), outputFile)
	f := must.M1(os.Create(outputPath))

	fmt.Fprintln(f, "// ***** This file is generated by internal/cmd/constraints_generator. DO NOT EDIT DIRECTLY. *****")
	fmt.Fprintln(f)

	if *flagTensors {
		fmt.Fprintln(f, "package tensors")
		fmt.Fprintln(f)
		fmt.Fprintln(f, "import (")
		fmt.Fprintln(f, "\t\"github.com/gomlx/compute/dtypes/bfloat16\"")
		fmt.Fprintln(f, "\t\"github.com/gomlx/compute/dtypes/float16\"")
		fmt.Fprintln(f, ")")
		fmt.Fprintln(f)
		fmt.Fprintln(f, "// MultiDimensionSlice lists the Go types a Tensor can be converted to/from.")
		fmt.Fprintln(f, "// There are no recursions in generics' constraint definitions,")
		fmt.Fprintln(f, "// so we list up to 5 levels of slices. Feel free to add")
		fmt.Fprintln(f, "// more if needed, as the implementation will work with any arbitrary number.")
		fmt.Fprintln(f)
		fmt.Fprintln(f, "// Generated by `github.com/gomlx/gomlx/internal/cmd/constraints_generator`.")
		fmt.Fprintln(f, "type MultiDimensionSlice interface {")
		TensorSlicesConstraints(f)
		fmt.Fprintln(f, "}")
		fmt.Fprintln(f)
	} else if *flagGraph {
		fmt.Fprintln(f, "package graph")
		fmt.Fprintln(f)
		fmt.Fprintf(f, "// For graph/exec.go:\n\n")
		GraphExecFnConstraints(f, false)
		fmt.Fprintln(f)
	} else if *flagModel {
		fmt.Fprintln(f, "package model")
		fmt.Fprintln(f)
		fmt.Fprintln(f, "import (")
		fmt.Fprintln(f, "\t\"github.com/gomlx/gomlx/core/graph\"")
		fmt.Fprintln(f, ")")
		fmt.Fprintln(f)
		fmt.Fprintf(f, "// For ml/model/exec.go:\n\n")
		GraphExecFnConstraints(f, true)
	}

	must.M(f.Close())
	cmd := exec.Command("go", "fmt", outputPath)
	klog.V(1).Infof("\t%s\n", cmd)
	cmd.Stderr = os.Stderr
	must.M(cmd.Run())

	fmt.Printf("✅ internal/cmd/constraints_generator: \tsuccessfully generated %s\n", outputPath)
}
