/***** File generated by ./internal/cmd/simplego_dispatcher: --dispatcher=dispatchWhere --generic=execWhereGeneric. Don't edit it directly. *****/

package simplego

import (
	"github.com/gomlx/gopjrt/dtypes"
	"github.com/gomlx/gopjrt/dtypes/bfloat16"
)

func init() {
	dispatchWhere.RegisterIfNotSet(dtypes.Int8, execWhereGeneric[int8])
	dispatchWhere.RegisterIfNotSet(dtypes.Int16, execWhereGeneric[int16])
	dispatchWhere.RegisterIfNotSet(dtypes.Int32, execWhereGeneric[int32])
	dispatchWhere.RegisterIfNotSet(dtypes.Int64, execWhereGeneric[int64])
	dispatchWhere.RegisterIfNotSet(dtypes.Uint8, execWhereGeneric[uint8])
	dispatchWhere.RegisterIfNotSet(dtypes.Uint16, execWhereGeneric[uint16])
	dispatchWhere.RegisterIfNotSet(dtypes.Uint32, execWhereGeneric[uint32])
	dispatchWhere.RegisterIfNotSet(dtypes.Uint64, execWhereGeneric[uint64])
	dispatchWhere.RegisterIfNotSet(dtypes.Float32, execWhereGeneric[float32])
	dispatchWhere.RegisterIfNotSet(dtypes.Float64, execWhereGeneric[float64])
	dispatchWhere.RegisterIfNotSet(dtypes.BFloat16, execWhereGeneric[bfloat16.BFloat16])
}
